package.json, tslint.json
Linting the project will become very handy once more people start contributing. 
Once there are no more lint error it would be worth adding `npm run lint` to a git pre-commit hook so that all the small errors get caught before they make it into the repository.
=> Add tslint for linting

package.json
Make `npm run build` platform agnostic by using platform independent build and clean scripts
=> Make npm run build work on windows

packages/requestNetwork.js/README.md, packages/requestNetworkSmartContracts/README.md
As discussed with @vrolland:
- duplicate word "Functions" in requestNetwork.js/README.md
- "packages" instead of "package" in requestNetworkSmartContracts/README.md
=> Fix typos in README.md

.circleci/config.yml, packages/requestNetwork.js/README.md, packages/requestNetwork.js/src/api/signed-request.ts, packages/requestNetwork.js/src/servicesContracts/requestBitcoinNodesValidation-service.ts, packages/requestNetwork.js/src/servicesContracts/requestERC20-service.ts, packages/requestNetwork.js/src/servicesContracts/requestEthereum-service.ts, packages/requestNetwork.js/test/unit/bitcoinNodesValidationServices/additionalsAction.ts, packages/requestNetwork.js/test/unit/bitcoinNodesValidationServices/broadcastSignedRequestAsPayer.ts, packages/requestNetwork.js/test/unit/bitcoinNodesValidationServices/createRequestAsPayee.ts, packages/requestNetwork.js/test/unit/bitcoinNodesValidationServices/signRequestAsPayee.ts, packages/requestNetwork.js/test/unit/bitcoinNodesValidationServices/subtractsAction.ts, packages/requestNetwork.js/test/unit/erc20Services/additionalsAction.ts, packages/requestNetwork.js/test/unit/erc20Services/broadcastSignedRequestAsPayer.ts, packages/requestNetwork.js/test/unit/erc20Services/createRequestAsPayee.ts, packages/requestNetwork.js/test/unit/erc20Services/createRequestAsPayer.ts, packages/requestNetwork.js/test/unit/erc20Services/paymentAction.ts, packages/requestNetwork.js/test/unit/erc20Services/signRequestAsPayee.ts, packages/requestNetwork.js/test/unit/erc20Services/subtractsAction.ts, packages/requestNetwork.js/test/unit/ethereumServices/additionalsAction.ts, packages/requestNetwork.js/test/unit/ethereumServices/broadcastSignedRequestAsPayer.ts, packages/requestNetwork.js/test/unit/ethereumServices/createRequestAsPayee.ts, packages/requestNetwork.js/test/unit/ethereumServices/createRequestAsPayer.ts, packages/requestNetwork.js/test/unit/ethereumServices/paymentAction.ts, packages/requestNetwork.js/test/unit/ethereumServices/signRequestAsPayee.ts, packages/requestNetwork.js/test/unit/ethereumServices/subtractsAction.ts
This PR contains some minor changes to improve readability of code/comments.
- replaced "positives integer" with "positive integers".
- renamed "isSignedRequestHasError" to "validateSignedRequest". The previous function name was unclear and grammatically awkward. What does the function do? It validates a signed Request - so let's call it `validateSignedRequest`.
- changed the reason used in test suite Request data to "purchased two large pizzas". Any serious organisation using Request will do their own code audit, and some might be put off by the previous reason. I also put the new data on IPFS, and updated the hashes/signatures for the relevant tests.
I also added a CircleCI config to validate my changes did not break any tests. You might want to exclude this as it duplicates the tests …
=> Fixed grammar in comments, improved a function name, changed purchase reason in tests

.circleci/config.yml
This PR extends the CircleCI pipeline in separate jobs to:
1. bootstrap the monorepo
2. run the library and contract tests
3. generate the documentation if the tests are successful
The CircleCI jobs and workflow in action can be seen here: https://circleci.com/gh/lrnt/requestNetwork
There are some things that could be improved/added in the future:
=> Extend CircleCI integration

packages/transaction-manager/specs/encryption.md
unsure about the other `data` fields, should they also be renamed `encryptedData`
Also, should this bump the version?
=> docs(encryption): typo in field name

packages/advanced-logic/specs/payment-network-eth-input-data-0.1.0-DRAFT.md, packages/request-client.js/src/api/payment-network/eth/payment-reference-calculator.ts, packages/request-client.js/test/api/payment-network/eth/info-retriever.test.ts, packages/request-client.js/test/index.test.ts
To remove the risk of error, we lowercase the parameters used to compute the payment reference
=> fix: use lowercase for payment reference

packages/utils/test/utils.test.ts
fix getCurrentTimestampInSecond() test to not fail randomly
https://requestnetwork.atlassian.net/browse/PROT-1057
=> test: fix getCurrentTimestampInSecond() test to not fail randomly

package.json, packages/advanced-logic/package.json, packages/data-access/package.json, packages/data-format/package.json, packages/epk-decryption/package.json, packages/epk-signature/package.json, packages/ethereum-storage/package.json, packages/integration-test/package.json, packages/multi-format/package.json, packages/request-client.js/package.json, packages/request-logic/package.json, packages/request-node/package.json, packages/toolbox/package.json, packages/transaction-manager/package.json, packages/types/package.json, packages/usage-examples/package.json, packages/utils/package.json, packages/web3-signature/package.json
Typescript [3.4 introduces incremental build with the tsconfig.tsbuildinfo](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html) files. Our `clean` script doesn't clean these files and leaves the repo in an inconsistent state. This PR adds the removal of these files to the `clean` command
=> chore: fix build issue with tsconfig.tsbuildinfo

packages/request-logic/src/actions/create.ts, packages/request-logic/test/unit/action.test.ts
Fixes retrocompatibility issue with requests older than 2.0.2. )
The request Id was being calculated after version changes, which resulted in a different id.
=> fix: fix old version id mismatch issue

packages/request-logic/package.json, yarn.lock
This reverts commit d5f644bd010157d388ffd15061e47b984d70357f.
The newer version of semver seems to have some smart lazy loading functionalities that break webpack (as usual with lazy loading).
It's not worth it to spend more time on this, we'll revert and upgrade when needed.
=> revert: bump semver from 5.6.0 to 7.1.1 (#102)

.circleci/config.yml, .dockerignore, Dockerfile
=> chore(CI): optimize docker build

.circleci/config.yml
Next releases were being released empty because we were not building before publishing.
Lerna does automatically run build when we do `lerna publish`, but something goes wrong in the process.
=> chore: add build step to next release

packages/integration-test/test/scheduled/btc.test.ts, packages/request-client.js/test/data-test.ts, packages/request-client.js/test/index.test.ts
- Reduce the number of call during the tests
- Skipping the nightly test for the testnet btc provider (issue posted on JIRA for a long term solution)
=> fix: reduce number of call to btc providers in the tests

packages/payment-detection/src/eth/info-retriever.ts
Add custom etherscan key as a quick fix for failing etherscan API calls.
Next step will be allowing the user to set their own etherscan key at the payment network declaration.
=> fix: add request custom etherscan key

packages/request-client.js/src/api/currency.ts, packages/request-client.js/test/api/currency.test.ts
The currency network was stateful, because the value stored in the map, which is a global variable, was changed. 
This PR removes the use of the global variable to avoid mistake.
```typescript
stringToCurrency('ETH')
// { type: RequestLogicTypes.CURRENCY.ETH, value: 'ETH' }
stringToCurrency('ETH-rinkeby')
// { type: RequestLogicTypes.CURRENCY.ETH, value: 'ETH', network: 'rinkeby' }
stringToCurrency('ETH')
// { type: RequestLogicTypes.CURRENCY.ETH, value: 'ETH', network: 'rinkeby' }
//                                                       ^~~~~~~~~~~~~~~~~~
```
=> fix: stateful currency network for ETH and BTC

packages/docs/docs/guides/3-Portal-API/5-api-conclusion.md
https://requestnetwork.atlassian.net/browse/PROT-
=> docs: API conclusion

packages/docs/docs/guides/3-Portal-API/3-api-apps.md
https://requestnetwork.atlassian.net/browse/PROT-
=> docs: Updated auth0 documentation for onboarding and authentication.

packages/payment-processor/src/payment/erc20-proxy.ts, packages/payment-processor/src/payment/eth-input-data.ts, packages/payment-processor/src/payment/index.ts, packages/payment-processor/src/payment/transaction-overrides.ts, packages/payment-processor/test/payment/erc20-proxy.test.ts, packages/payment-processor/test/payment/eth-input-data.test.ts
Allow overriding transaction parameters, like gasPrice
=> feat: payment-processor transaction overrides

packages/data-format/src/format/rnf_invoice/rnf_invoice-0.0.2.json, packages/data-format/test/data/example-valid-0.0.2.json
Add company registration to buyerInfo in rnf-invoice.
This is a bug, since this data was already on specs. Also, it's an optional extra field, so we don't need to create a new version
=> fix: company registration on rnf_invoice

packages/request-node/src/request/persistTransaction.ts
Catches the error on the node persist transaction, so it doesn't throw.
Also logs the errored transaction, helping us recover it from the logs in case it's lost.
https://requestnetwork.atlassian.net/browse/PROT-1211
=> fix: intercept error and log the missed transaction

packages/request-node/package.json
Bumps @types/express from 4.16.1 to 4.17.7
=> build(deps-dev): bump @types/express from 4.16.1 to 4.17.7

packages/ethereum-storage/package.json, packages/integration-test/package.json, packages/web3-signature/package.json, yarn.lock
Small increment on web3 dependency (the highest we can go without making more changes to the codebase now), that unblocks the nodejs version (seems we can use up to the most recent version).
=> build(dep): upgrade web3 from 1.2.0 to 1.2.1

packages/payment-processor/src/index.ts, packages/payment-processor/src/payment/erc20-fee-proxy.ts, packages/payment-processor/src/payment/erc20-proxy.ts, packages/payment-processor/src/payment/erc20.ts, packages/payment-processor/src/payment/index.ts, packages/payment-processor/test/payment/erc20-fee-proxy.test.ts, packages/payment-processor/test/payment/erc20-proxy.test.ts, packages/payment-processor/test/payment/erc20.test.ts, packages/payment-processor/test/payment/index.test.ts
The separate APIs for ERC20 proxy and ERC20 fees proxy are unnecessary and confusing.
On this PR we merge both APIs into one.
=> feat: unify ERC20 payment processing API

packages/docs/docusaurus.config.js, packages/docs/src/components/redoc.js, packages/docs/src/pages/portal/index.js, packages/docs/webpack-config/index.js
Some dependencies from ReDoc were having issues with the build (missing Buffer). 
More info [here](https://github.com/isaacs/core-util-is/issues/27) and [here](). There is an issue open [here](https://github.com/isaacs/core-util-is/issues/29).
=> fix(docs): fix missing buffer

packages/ethereum-storage/src/ipfs-manager.ts, packages/ethereum-storage/test/ipfs-manager.test.ts
During the "chunk size test", we decode from base64 before checking the size of the file downloaded.
=> fix: ipfs manager read() decode from base64 before checking the size 

packages/request-client.js/test/index.test.ts
Temporarilly skip failing tests using etherscan.
=> fix: skip failing etherscan tests

packages/docs/docusaurus.config.js, packages/docs/package.json, yarn.lock
Upgrade docusaurus to beta-64.
Use docusaurus-plugin-typedoc to generate typescript documentation for the `request-client.js` library.
Clean up and optimize docs run and build times.
=> chore: improve request client docs generation

packages/smart-contracts/artifacts/ERC20SwapToPay/artifacts.json, packages/smart-contracts/artifacts/verification/ERC20SwapToPay.sol/ERC20SwapToPay.sol, packages/smart-contracts/artifacts/verification/ERC20SwapToPay.sol/SafeERC20.sol, packages/smart-contracts/src/contracts/ERC20SwapToPay.sol, packages/smart-contracts/src/contracts/lib/SafeERC20.sol, packages/smart-contracts/test/contracts/ERC20SwapToPay.js
* Handle ERC20 tokens that do not implement approve() with a bool return as the standard suggests
=> fix: swap methods for partial ERC20 approvals

packages/payment-processor/src/payment/erc20.ts
Ended up being a simple fix but hard to debug. The hasErc20Approval is async but we don't `await` for the result which meant prompts for approvals were never getting triggered
=> fix: erc20 approval

packages/data-format/README.md, packages/data-format/src/format/rnf_invoice/README.md, packages/data-format/src/format/rnf_invoice/rnf_invoice-0.0.3.json, packages/data-format/test/data/example-invalid-0.0.3.json, packages/data-format/test/data/example-valid-0.0.3.json
Use string instead of number to represent tax amount.
Update documentation.
=> fix: use string for rnf_invoice tax amount

.eslintrc, packages/request-client.js/src/api/currency/erc20.ts, packages/request-client.js/src/api/currency/erc20/celo.ts, packages/request-client.js/src/api/currency/erc20/networks.ts, packages/request-client.js/src/api/currency/erc20/rinkeby.ts, packages/request-client.js/test/api/currency.test.ts, packages/request-client.js/test/api/currency/erc20.test.ts, packages/request-client.js/test/index-encryption.html
- Add support to Celo network to ERC20 currencies.
- Add cUSD to ERC20 currencies.
- Make ERC20 networks support generic and extensible.
This PR does not add Celo network support to ERC20 payment networks, only the currency (currently only usable with declarative requests).
=> feat: add currency support to Celo network and CUSD

.circleci/config.yml
Tries to fix lerna canary release (for nightlies) by force-publishing all the changed packages since last release (and not only the ones changed at the last commit).
Based on this thread: https://github.com/lerna/lerna/issues/2060#issuecomment-619403848
This is a hack and should be addressed in the future, probably by migrating to a better tool (like Nx, Rush, multi-semantic-release) or using our own publishing script (simple if we want to use fixed versions for all packages).
=> fix: use force push to fix lerna broken nightly updates

packages/smart-contracts/package.json, packages/smart-contracts/src/contracts/ERC20Proxy.sol, packages/smart-contracts/src/contracts/RequestHashStorage.sol, packages/smart-contracts/src/contracts/StorageFeeCollector.sol, yarn.lock
`@openzeppelin/contracts` and `openzeppelin-solidity` are the same package.
We were using both on our codebase. This PR removes the older alias `openzeppelin-solidity`.
=> build: get rid of duplicate open-zepellin contract dependency

.circleci/config.yml
It seems the .ssh is not kept between the build image and the publish image. 
Moving the step to where it's necessary.
=> fix: move circleci github ssh key to release step

packages/smart-contracts/package.json
Typo in the github URL that breaks the NPM link
=> chore: fix typo in URL [skip ci]

packages/utils/package.json, packages/utils/src/crypto.ts, packages/utils/src/crypto/ec-utils.ts, packages/utils/src/signature.ts, packages/utils/test/crypto/ec-utils.test.ts, yarn.lock
`eth-crypto` is a nice lib but it has too many dependencies, which makes it really hard to maintain our packages.
Being a dependency of `@requestnetwork/utils`, all other packages depend on it. 
Removing it reduces by >1/4 the size of the request-client.js lib.
=> chore: remove eth-crypto from utils

packages/smart-contracts/artifacts/ChainlinkConversionPath/artifacts.json, packages/smart-contracts/artifacts/Erc20ConversionProxy/artifacts.json
Following an error in the deployment of the Chainlink conversion path contract (wrong version of the contract used), both ChainlinkConversionPath and ERC20ConversionProxy contract artifacts require an update
=> fix: Chainlink contracts updates

packages/currency/README.md, packages/currency/src/chainlink-path-aggregators.ts, packages/currency/src/currency.ts, packages/currency/src/erc20/index.ts, packages/currency/src/erc20/networks/rinkeby.ts, packages/currency/src/index.ts, packages/currency/src/token.ts, packages/currency/test/currency.test.ts, packages/currency/test/token.test.ts, packages/payment-detection/src/any/any-to-erc20-proxy-info-retriever.ts, packages/request-client.js/src/api/request-network.ts, packages/request-client.js/src/api/request.ts, packages/toolbox/src/chainlinkConversionPathTools.ts
Motivation: ease the use of the different helpers we have for currencies.
This is a first step, we should migrate all the similar utilities to class or object method, IMO.
* chore: Token an Currency classes design
* feat: fetch a currency from its address with `Currency.from(...)`
=> chore: Token and Currency classes

packages/currency/README.md, packages/currency/src/currency.ts, packages/currency/src/erc20/networks/mainnet.ts, packages/currency/src/index.ts, packages/currency/src/token.ts, packages/currency/test/currency.test.ts, packages/currency/test/token.test.ts, packages/payment-detection/src/any/any-to-erc20-proxy-info-retriever.ts, packages/payment-processor/src/payment/any-to-erc20-proxy.ts, packages/request-client.js/src/api/utils.ts
chore: deprecate getDecimalsForCurrency, replaced with currency.getDecimals()
fix: Currency.from() for lower case addresses
=> chore: currency.getDecimals() and fixes

packages/advanced-logic/src/extensions/payment-network/erc20/fee-proxy-contract.ts
Note: we miss unit tests for `applyCreation()`, I add it to the backlog
=> fix: error message when payment address is missing

packages/payment-processor/src/payment/any-to-erc20-proxy.ts, packages/payment-processor/src/payment/utils.ts, packages/payment-processor/test/payment/utils.test.ts
This PR fixes the bug that makes it impossible to pay a request denominated in crypto with another crypto with on-payment conversion.
=> fix: amount padding for conversion of crypto amounts

packages/payment-detection/src/index.ts, packages/payment-detection/test/utils.test.ts, packages/toolbox/src/chainlinkConversionPathTools.ts
Code climate was complaining about it, it's not a big deal but it could prevent some mistakes.
=> chore: re-use parseLogArgs

packages/payment-detection/src/eth/info-retriever.ts, packages/payment-detection/src/eth/input-data.ts, packages/payment-detection/src/eth/multichainExplorerApiProvider.ts, packages/payment-detection/src/payment-network-factory.ts, packages/payment-detection/src/provider.ts, packages/payment-detection/test/eth/info-retriever.test.ts, packages/payment-detection/test/payment-network-factory.test.ts, packages/request-client.js/src/api/request-network.ts
Add a default RPC url for fantom and fuse (useful in frontend and low-usage calls), and remove the default etherscan API key that is only usable for etherscan, not ftmscan & co.
=> feat: fantom/fuse RPC url & explorer api key per network

packages/currency/src/currency.ts, packages/currency/src/native.ts, packages/currency/test/currency.test.ts
- Fix cases such as Currency.fromSymbol('NEAR-testnet')
- Re-organize a bit tests to split Currency.from and Currency.fromSymbol (no test was removed)
=> fix: Currency.fromSymbol for testnets of native tokens

packages/currency/src/currency.ts, packages/currency/test/currency.test.ts, packages/currency/test/token.test.ts
- Tests NEAR token & currency methods
- Handle `NEAR-near`
=> fix: handle NEAR-near legacy naming

packages/advanced-logic/src/extensions/payment-network/near-native.ts, packages/advanced-logic/test/utils/payment-network/any/generator-data-create.ts, packages/payment-detection/src/near-detector.ts, packages/payment-detection/src/near-info-retriever.ts, packages/payment-detection/test/near-native.test.ts, packages/payment-processor/src/payment/near-input-data.ts, packages/payment-processor/src/payment/utils-near.ts, packages/payment-processor/src/payment/utils.ts, packages/payment-processor/test/payment/index.test.ts
feat: Near contract will drop the references to `amount` (extension version 0.2.0)
chore: improved testing coverage
=> feat: upgrade near references to 0.2.0

.vscode/settings.json, packages/payment-detection/src/payment-network-factory.ts, packages/payment-detection/test/near-native.test.ts, packages/payment-detection/test/payment-network-factory.test.ts, packages/request-client.js/src/api/request-network.ts, packages/request-client.js/test/index.test.ts
The currencyManager is not passed down the Payment Network when the PN is constructed from the Request.
=> fix: currencyManager in PN factory from request

packages/smart-contracts/package.json, packages/smart-contracts/test/contracts/ChainlinkConversionPath.test.ts, yarn.lock
Merging 2 tests because they are stateful, and based on the same instance of ganache, meaning the state of the contract was not 0x000 at the beginning of the test.
`chai` was imported with `require`, so there was no typing.
Because there was no typing, it was not highlighted that the `expect` was wrong
It was missing the `equal` call, without which the call was useless.
=> test: fix wrong chainlink test

packages/payment-processor/src/payment/index.ts
* Since Gnosis is now a dedicated provider, we need to fix the check for ETH solvency need
=> fix: don't check ETH solvency for a Gnosis provider

packages/advanced-logic/src/extensions/abstract-extension.ts, packages/advanced-logic/src/extensions/content-data.ts, packages/advanced-logic/src/extensions/payment-network/address-based.ts, packages/advanced-logic/src/extensions/payment-network/declarative.ts, packages/advanced-logic/src/extensions/payment-network/reference-based.ts, packages/advanced-logic/test/extensions/content-data.test.ts, packages/advanced-logic/test/extensions/payment-network/any-to-erc20-proxy.test.ts, packages/advanced-logic/test/extensions/payment-network/bitcoin/mainnet-address-based.test.ts, packages/advanced-logic/test/extensions/payment-network/bitcoin/testnet-address-based.test.ts, packages/advanced-logic/test/extensions/payment-network/declarative.test.ts, packages/advanced-logic/test/extensions/payment-network/erc20/address-based.test.ts, packages/advanced-logic/test/extensions/payment-network/erc20/fee-proxy-contract.test.ts, packages/advanced-logic/test/extensions/payment-network/erc20/proxy-contract.test.ts, packages/advanced-logic/test/extensions/payment-network/ethereum/fee-proxy-contract.test.ts, packages/advanced-logic/test/extensions/payment-network/ethereum/input-data.test.ts, packages/advanced-logic/test/extensions/payment-network/native-token.test.ts, packages/advanced-logic/test/utils/payment-network/erc20/fee-proxy-contract-create-data-generator.ts
⚠️  Please review carefully and challenge that the bug is indeed a bug!
The Payment Processor should use the contract matching the version of the PN.
A bug fix in Payment Processor was done earlier https://github.com/RequestNetwork/requestNetwork/pull/556
This new bug, not related to the previous, is that the extension version is not based on the stored data, but defaults to the `CURRENT_VERSION` of the extension. 
- rely on the abstract extension for `id`, `type` and `version`
- throw if there was no `version` at creation
- tests: test each payment network individually, since regression could have important impacts
=> fix: extension version not based on data

packages/currency/src/currencyManager.ts, packages/currency/test/currencyManager.test.ts
Allow getting currency by its id. Example usage is for `ETH-rinkeby-rinkeby`
=> fix: allow id to be used for .from method

package.json
Adds a new yarn command to make all `requestNetwork` packages available as symlinks in  `~/.config/yarn/link/@requestnetwork/` in order to be able to work with them dynamically in external projects.
=> feat: yarn link:all

packages/advanced-logic/src/extensions/payment-network/erc20/fee-proxy-contract.ts, packages/advanced-logic/src/extensions/payment-network/ethereum/input-data.ts, packages/currency/src/erc20/networks/bsc.ts, packages/currency/src/erc20/networks/index.ts, packages/currency/src/native.ts, packages/payment-detection/src/eth/multichainExplorerApiProvider.ts, packages/payment-detection/src/provider.ts, packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20FeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/Erc20ConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumProxy/index.ts, yarn.lock
=> feat: bsc payments except swap

packages/advanced-logic/specs/payment-network-any-to-erc20-proxy-0.1.0.md, packages/advanced-logic/specs/payment-network-erc20-fee-proxy-contract-0.1.0.md, packages/advanced-logic/specs/payment-network-eth-fee-proxy-contract-0.1.0.md, packages/advanced-logic/specs/payment-network-eth-input-data-0.2.0.md, packages/advanced-logic/src/extensions/payment-network/declarative.ts, packages/payment-detection/src/declarative.ts, packages/payment-detection/test/declarative.test.ts, packages/request-client.js/src/api/request.ts, packages/request-client.js/test/index.test.ts, packages/types/src/extensions/pn-any-declarative-types.ts, packages/types/src/payment-types.ts
Adding `network` as parameters. As discussed with @benjlevesque , `txHash` is not enough as the manual payment can be made in a different network than the expected payment method (e.g a request is expected to be paid in USDT but the payment is made in Polygon)
=> feat: add network as declarative params

packages/docs/docs/guides/0-getting-started.md, packages/docs/docs/guides/3-Portal-API/2-payment-status.md, packages/docs/docs/guides/3-Portal-API/5-api-conclusion.md
Build is now failing if `keywords` doesn't contain an array.
=> fix: remove empty keywords

packages/advanced-logic/src/extensions/payment-network/declarative.ts
`txHash` and `network` needs to be injected to `request.extensions[paymentNetworkId].events[i].parameters` in order to make it available on `balance.events[i].parameters`
=> fix: add txHash and network to extensions events

packages/payment-detection/src/thegraph/queries/GetLastSyncedBlock.graphql, packages/payment-detection/src/thegraph/queries/GetSyncedBlock.graphql
This PR adds a new GraphQL query to check if a block hash has been parsed by a specific subgraph.
=> feat: payment detection thegraph block hash

packages/payment-detection/src/any-to-any-detector.ts, packages/payment-detection/src/any/any-to-erc20-proxy.ts, packages/payment-detection/src/any/any-to-eth-proxy.ts, packages/payment-detection/src/declarative.ts, packages/payment-detection/src/erc20/fee-proxy-contract.ts, packages/payment-detection/src/erc20/proxy-contract.ts, packages/payment-detection/src/eth/fee-proxy-detector.ts, packages/payment-detection/src/eth/input-data.ts, packages/payment-detection/src/fee-reference-based-detector.ts, packages/payment-detection/src/index.ts, packages/payment-detection/src/near-detector.ts, packages/payment-detection/src/payment-network-factory.ts, packages/payment-detection/src/reference-based-detector.ts, packages/payment-detection/test/declarative.test.ts, packages/payment-detection/test/payment-network-factory.test.ts, packages/request-client.js/src/api/request.ts
- naming: `DeclarativePaymentDetector` instead of various names
- harmonize usage of  `PaymentTypes.PAYMENT_NETWORK_ID`.
- enforce passing `PaymentTypes.PAYMENT_NETWORK_ID` and the extension as constructor params to avoid forgetting overriding this property in a child class. **This is the main motivation of this PR**. For this to work properly, I sometimes introduced a `-Base` class to keep the current class constructor signature and have a better extensibility
=> refactor: payment detectors inheritance

packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/0.1.0.json
The ABI stored in the Artifacts seem to not match the contract
=> fix: artifact ABI for ChainlinkConversionPath

packages/request-node/Dockerfile.dev, packages/request-node/README.md
It can be very useful to be able to rapidly build the Request Node with the latest build from all packages. 
I found this to be the best config, as it takes a few seconds to build the whole monorepo (typescript only) and the request-node with [NCC](https://github.com/vercel/ncc)
=> chore: Dockerfile.dev

packages/payment-detection/src/thegraph/index.ts
Our fantom's subgraph has a constant synchronization delay of ~100 to 500 blocks, which causes payment detection to be delayed by 10-15mins. This temporarily disables using TheGraph for payment detection until we fix the subgraph's delay.
=> chore(payment-detection): disable TheGraph support for fantom

packages/smart-contracts/package.json
- The devDependency was breaking some `smart-contracts` imports like in `payments-subgraph`
=> fix: tslib dependency in smart-contracts

.circleci/config.yml, packages/data-access/package.json
Adds `--maxWorkers=1` to test commands in CI to prevent Jest from spawning 31 workers on VMs with only 2vCPU, resulting in failing tests, like here: https://app.circleci.com/pipelines/github/RequestNetwork/requestNetwork/5348/workflows/c6e3c200-7b29-4afa-8756-6367e04310fa/jobs/86870/steps
`maxWorkers` should be set to amount of CPUs minus one for Jest's main thread, so `2-1=1` for CircleCI's medium Docker executor that has 2vCPU.
The reason it is spawning 31 workers is that CircleCI hosts have 32 (real) CPUs, making Jest think it is running on a 32 cores machines whereas it is running on a 2vCPU machine.
See: https://support.circleci.com/hc/en-us/articles/360005442714-Your-test-tools-are-smart-and-that-s-a-problem-Learn-about-when-optimization-goes-wrong-
=> ci: adjust jest maxWorkers

packages/data-access/package.json, packages/data-access/src/data-access.ts, packages/data-access/src/interval-timer.ts, packages/data-access/test/data-access.test.ts, packages/data-access/test/interval-timer.test.ts
The `--forceExit` option was added to `data-access` tests in https://github.com/RequestNetwork/requestNetwork/pull/735 because, when using only one worker, Jest does not close its process automatically if there is still open handles.
This PR fixes `data-access` so that the synchronization stop waits for the last recursion to finish.
=> test(data-access): remove forceExit option

.circleci/config.yml
Reverts RequestNetwork/requestNetwork#737 because `next-release` fails with an OOM error since then.
=> Revert "ci: use ram disk"

packages/advanced-logic/specs/payment-network-any-to-eth-proxy-0.1.0.md, packages/smart-contracts/scripts/3_deploy_chainlink_contract.ts, packages/smart-contracts/scripts/deploy-payments.ts, packages/smart-contracts/scripts/utils.ts, packages/smart-contracts/src/contracts/ChainlinkConversionPath.sol, packages/smart-contracts/src/contracts/EthConversionProxy.sol, packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/0.2.0.json, packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/index.ts, packages/smart-contracts/src/lib/artifacts/EthConversionProxy/0.2.0.json, packages/smart-contracts/src/lib/artifacts/EthConversionProxy/index.ts, packages/smart-contracts/test/contracts/EthConversionProxy.test.ts
ChainlinkConversionPath v0.2.0
- Configure the native token hash in the constructor of Chainlink conversion path
ETHConversionProxy v0.2.0
- Whitelisted admins can edit the conversion path contract
- Whitelisted admins can edit the proxy contract
Live payment script:
- nonce 10: ChainlinkConversionPath v0.2.0
- nonce 11: ETHConversionProxy v0.2.0
=> fix(contract): ETH conversion native hashes per chain

packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20FeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/Erc20ConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumFeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumProxy/index.ts
Change name from arbitrum-testnet to arbitrum-rinkeby for subgraph compatibility
=> fix: arbitrum-testnet-naming

packages/payment-detection/README.md, packages/payment-detection/src/any/retrievers/thegraph.ts, packages/payment-detection/src/erc20/address-based-info-retriever.ts, packages/payment-detection/src/erc20/escrow-info-retriever.ts, packages/payment-detection/src/erc20/proxy-info-retriever.ts, packages/payment-detection/src/eth/info-retriever.ts, packages/payment-detection/src/eth/proxy-info-retriever.ts, packages/payment-detection/src/payment-network-factory.ts, packages/payment-detection/src/types.ts, packages/types/src/payment-types.ts
- Revamped README
- Renamed `IPaymentNetworkInfoRetriever` > `IPaymentRetriever`
- Renamed `IPaymentNetworkBaseInfoRetriever` > `IEventRetriver`
- Moved the definition of retrievers from `types` to `payment-detection`
=> chore(payment-detection): clean Retrievers type. Document.

packages/smart-contracts/hardhat.config.ts, packages/smart-contracts/scripts/3_deploy_chainlink_contract.ts, packages/smart-contracts/scripts/conversion-proxy.ts, packages/smart-contracts/scripts/deploy-one.ts, packages/smart-contracts/scripts/deploy-payments.ts, packages/smart-contracts/scripts/erc20-swap-to-conversion.ts, packages/smart-contracts/scripts/utils.ts, packages/smart-contracts/src/contracts/ERC20SwapToConversion.sol, packages/smart-contracts/src/contracts/Erc20ConversionProxy.sol, packages/smart-contracts/src/lib/artifacts/Erc20ConversionProxy/0.1.1.json, packages/smart-contracts/src/lib/artifacts/Erc20ConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/Erc20SwapConversion/0.1.0.json, packages/smart-contracts/src/lib/artifacts/Erc20SwapConversion/index.ts
* Erc20ConversionProxy.sol 0.1.1 with setPaymentProxy in order to deploy erc20ConversionProxy before ChainlinkConversionPath on future chains where we only deploy ChainlinkConversionPath 0.2.0 (afterwards)
* deployment script updated to deploy the full suite of contracts
=> fix: deployment script with ERC20Conversion v2 and Swap

packages/ethereum-storage/src/gas-price-definer.ts, packages/ethereum-storage/src/index.ts, packages/ethereum-storage/src/smart-contract-manager.ts, packages/ethereum-storage/test/gas-price-definer.test.ts, packages/request-node/package.json, packages/request-node/src/thegraph/TheGraphStorage.ts, yarn.lock
Gas limit can be too low for transactions submitted through `TheGraphDataAccess`. This adds an EIP-1559 gas price estimation for transactions submitted with this data access implementation.
=> chore(request-node): eip-1559 for TheGraphDataAccess

packages/request-node/src/thegraph/TheGraphStorage.ts
Call to `eth_feeHistory` was always failing due to missing parameters.
=> fix(request-node): eth_feeHistory missing parameters

packages/data-format/src/format/rnf_invoice/utils.ts, packages/data-format/test/rnf_invoice/utils.test.ts
Fixes edge cases where we lost precision.
e.g. :
`item.unitPrice = 33.33`
`item.quantity = 1`
`item.tax.amount = 20`
`item.discount = 0`
The "true" result is `39.996`. This function returned `39.99`, it now returns `40.00`.
=> fix: price calculation

packages/payment-processor/src/index.ts, packages/payment-processor/src/payment/any-to-erc20-proxy.ts, packages/payment-processor/src/payment/any-to-eth-proxy.ts, packages/payment-processor/src/payment/conversion-erc20.ts, packages/payment-processor/src/payment/erc20-fee-proxy.ts, packages/payment-processor/src/payment/erc20-proxy.ts, packages/payment-processor/src/payment/erc20.ts, packages/payment-processor/src/payment/eth-fee-proxy.ts, packages/payment-processor/src/payment/eth-input-data.ts, packages/payment-processor/src/payment/eth-proxy.ts, packages/payment-processor/src/payment/swap-any-to-erc20.ts, packages/payment-processor/src/payment/swap-conversion-erc20.ts, packages/payment-processor/src/payment/swap-erc20-fee-proxy.ts, packages/payment-processor/src/payment/swap-erc20.ts
Refactoring of the payment-processor package.
Before:
- For some payment methods we had signing, preparing and encoding functions, in others only signing and encoding.
- Same kind of issue for approval functions.
- In some files we used `Web3Provider `in other `Provider`
Now:
- All payment methods have signing, preparing and encoding functions.
- All kind of approvals have distinct `approvefNeeded`, `hasApproval` and `prepareApproval` functions 
- All files use `Provider` which allows to pass `ethers.providers.JsonRpcProvider` which can be useful if we only want to prepare a transaction and sign it externally.
=> refactor: payment-processor

packages/smart-contracts/src/contracts/EthereumFeeProxy.sol, packages/smart-contracts/src/contracts/EthereumProxy.sol, packages/smart-contracts/src/contracts/test/EtherFallbackPayment.sol, packages/smart-contracts/src/contracts/test/GnosisProxy.sol, packages/smart-contracts/test/contracts/EthConversionProxy.test.ts, packages/smart-contracts/test/contracts/EthereumFeeProxy.test.ts, packages/smart-contracts/test/contracts/EthereumProxy.test.ts
Enables to pay requests in ether when the recipient is a proxy smart contract, like smart wallet such as Gnosis Safe.
The `.transfer` is limited to 2300 gas, so when a payment recipient was a Gnosis Safe, we did not pass enough gas for it to execute it's fallback function. I changed it to `.call` which pass all the remaining transaction gas.
New tests cover for this specific case.
=> feat: ether to smart wallet payment

packages/payment-processor/src/index.ts, packages/payment-processor/src/payment/encoder-approval.ts, packages/payment-processor/src/payment/encoder-payment.ts, packages/payment-processor/src/payment/index.ts, packages/payment-processor/test/payment/encoder-approval.test.ts, packages/payment-processor/test/payment/encoder-payment.test.ts, packages/payment-processor/test/payment/encoder.test.ts
It exports new methods from the `payment-processor` package:
- Encoding of the approval transaction for a request payment
- Check for knowing if an approval is needed for a request payment
- Encoding of an approval transaction if needed for a request payment
- Encoding of the payment transaction for a request payment
- Encoding of all necessary transactions (approval if needed + payment) for a request payment
New tests cover these methods
=> feat: transaction encoding

packages/payment-detection/src/erc20/thegraph-info-retriever.ts, packages/payment-detection/test/erc20/thegraph-info-retriever.test.ts
Updated GraphInfoRetriever to return ERC20Fee events that also contain feeAddress and feeAmount
=> fix: changed graph getTransferEvents return types into IERC20Fee

.lintstagedrc.json
Now that we apply `prettier` on every file, we need to apply `lint-staged` on every file types too, so that `husky` could work properly.
=> chore: apply lint-staged on every file types

packages/currency/src/chainlink-path-aggregators.ts, packages/currency/src/erc20/networks/bsc.ts, packages/smart-contracts/hardhat.config.ts, packages/smart-contracts/scripts/utils.ts, packages/smart-contracts/src/lib/artifacts/ERC20SwapToPay/index.ts, packages/smart-contracts/src/lib/artifacts/Erc20SwapConversion/index.ts, packages/smart-contracts/src/lib/artifacts/EthConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumFeeProxy/index.ts, packages/toolbox/README.md, packages/toolbox/src/commands/chainlink/addAggregators.ts, packages/toolbox/src/commands/chainlink/aggregatorsUtils.ts
fix: `toolbox` addAggregators was missing some currencies with equivalent on mainnet
depl: BSC deployments of `EthConversion`, `EthFeeProxy` (0.1.0), `Erc20SwapToPay` and `Erc20SwapWithConversion`
chore: `toolbox` clarified the documentation for addAggregators
=> feat: deployments on bsc aggregator

packages/payment-detection/src/erc20/escrow-info-retriever.ts, packages/payment-detection/src/index.ts, packages/payment-detection/test/erc20/escrow-info-retriever.test.ts, packages/request-client.js/src/api/request.ts, packages/request-client.js/test/api/request.test.ts, packages/types/src/payment-types.ts
This ads a method for reading data from the Escrow smart contract directly to the EscrowInfoRetriever.
We need to read data from a mapping in the Escrow contract to be able to figure out some deadlines when freezing funds etc.
This data is not broadcasted in any events so the only way to get it is from the contract directly.
This new function is exposed to 3rd party users via request-client.js, within the Request class.
=> feat: retrieve active escrow data

packages/data-format/src/format/rnf_invoice/rnf_invoice-0.0.3.json, packages/smart-contracts/hardhat.config.ts, packages/smart-contracts/scripts/5_deploy-batch-erc-eth-deployment.ts, packages/smart-contracts/scripts/6_deploy-all.ts, packages/smart-contracts/src/contracts/BatchPayments.sol, packages/smart-contracts/src/contracts/interfaces/EthereumFeeProxy.sol, packages/smart-contracts/src/lib/artifacts/BatchPayments/0.1.0.json, packages/smart-contracts/src/lib/artifacts/BatchPayments/index.ts, packages/smart-contracts/src/lib/artifacts/index.ts, packages/smart-contracts/test/contracts/BatchErc20Payments.test.ts, packages/smart-contracts/test/contracts/BatchEthPayments.test.ts
Add BatchPayment smart contract and tests, to do batch payments with ERC20 tokens and Ethers, with multiple recipients addresses, and possibly multiple tokens in a batch.
Main functions:
- batchEthPaymentsWithReference
- batchERC20PaymentsWithReference
- batchERC20PaymentsMultiTokensWithReference
The owner of the contract manages:
- feeBatch: between 0 and 1000, initialized at 0. 
ex: batchFee = 10 is equivalent to 1.0% of batch fee
- ERC20FeeProxy address
- EthereumFeeProxy address
=> feat: Batch payments erc20 eth

packages/payment-processor/src/payment/index.ts
NATIVE_TOKEN was not registered as a supported network, leading the solvency check to fail when using near.
=> fix-near-solvency

packages/ethereum-storage/test/ipfs-storage.test.ts
Non-existent DNS resolution can take more than 1s, cf https://app.circleci.com/pipelines/github/RequestNetwork/requestNetwork/6191/workflows/5ea87810-802d-4050-a4b4-3b9424785d71/jobs/102393
=> test(ipfs-storage): increase timeout for bad DNS resolution

packages/currency/src/getHash.ts
add missing support of ERC777 currency type in the getHash function even if it's not needed yet because hash is well precised for fDAIX-rinkeby
=> fix: add ERC777 support to getHash

packages/payment-detection/src/erc20/escrow-info-retriever.ts, packages/payment-processor/src/index.ts, packages/payment-processor/src/payment/erc20-escrow-payment.ts, packages/payment-processor/test/payment/erc20-escrow-payment.test.ts
1. Exposing function for getting escrow contract deployment info. This was missing because Escrow is not a PN yet and has no separate PaymentDetector.
2. Exposing IPreparedTransaction to be used in Portal transaction builder.
3. Removed unnecessary requirement for provider in Escrow transaction encoding functions.
=> feat: escrow deployment info

.circleci/config.yml
This PR fixes the version of the [request-ipfs](https://hub.docker.com/r/requestnetwork/request-ipfs/tags?page=1) docker image used in our CI tests.
=> fix(ci): rollback ipfs docker image version

.circleci/config.yml, packages/payment-detection/src/erc777/superfluid-retriever.ts, packages/payment-detection/test/erc777/superfluid-retriever.test.ts
Fix the pattern queried by payment-detection in SuperFluid subgraph, it should be exactly the same pattern than what is sent by payment-processor.
It hasn't been deteted by the unit tests because they mock the result of the subgraph queries.
=> fix: detect in subgraph same reference than paid

packages/payment-detection/src/erc777/superfluid-retriever.ts, packages/payment-detection/test/erc777/superfluid-retriever.test.ts
to fix the errors in sync-api due to the lack of block number in the payment detection for SuperFluid payment network.
=> fix: fill block and txHash parameters in events

packages/payment-detection/src/erc20/thegraph-info-retriever.ts, packages/payment-detection/src/thegraph/queries/GetPaymentsAndEscrowState.graphql, packages/payment-detection/test/erc20/fee-proxy-contract.test.ts
ticket: https://app.asana.com/0/1187210138355031/1202055267731943/f
- pull `gasUsed` & `gasPrice` field from updated payment subgraph graphql query
- store fields into request object
=> feat: pull gas info field from subgraph

packages/request-client.js/src/api/request.ts, packages/request-node/src/request/getChannelsByTopic.ts, packages/request-node/src/request/getTransactionsByChannelId.ts, packages/request-node/src/request/persistTransaction.ts, packages/request-node/src/thegraph/CombinedDataAccess.ts, packages/request-node/src/thegraph/PendingStore.ts, packages/request-node/src/thegraph/TheGraphDataAccess.ts, packages/request-node/src/thegraph/index.ts, packages/types/src/data-access-types.ts
This enables relying on the request-node to persist the transaction, and on the graph-node to confirm it
=> feat: split data-access read and write for TheGraph

packages/smart-contracts/scripts-create2/contract-setup/adminTasks.ts, packages/smart-contracts/scripts-create2/contract-setup/setupBatchPayments.ts
- update batch fees from 1% to .3%, on every networks
- increase gas price when updating batch contract: without it, it fails
- add logs when updating batch fees
=> fix(smart-contracts): update batch fees

packages/payment-processor/src/payment/erc777-stream.ts, packages/payment-processor/test/payment/erc777-stream.test.ts
Add function to cancel stream paying a request, to be called from Request Finance UI.
=> feat: add cancel stream function

packages/currency/src/native.ts, packages/smart-contracts/README.md, packages/smart-contracts/hardhat.config.ts, packages/smart-contracts/scripts-create2/compute-one-address.ts, packages/smart-contracts/scripts-create2/constructor-args.ts, packages/smart-contracts/scripts-create2/contract-setup/setupETHConversionProxy.ts, packages/smart-contracts/scripts-create2/contract-setup/setups.ts, packages/smart-contracts/scripts-create2/deploy-one.ts, packages/smart-contracts/scripts-create2/deploy-request-deployer.ts, packages/smart-contracts/scripts-create2/deploy.ts, packages/smart-contracts/scripts-create2/utils.ts, packages/smart-contracts/scripts-create2/verify-one.ts, packages/smart-contracts/scripts-create2/verify.ts, packages/smart-contracts/src/lib/artifacts/BatchPayments/index.ts, packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20EscrowToPay/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20FeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20SwapToPay/index.ts, packages/smart-contracts/src/lib/artifacts/Erc20ConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/Erc20SwapConversion/index.ts, packages/smart-contracts/src/lib/artifacts/EthConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumFeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumProxy/index.ts, packages/smart-contracts/src/lib/artifacts/RequestDeployer/index.ts, packages/smart-contracts/src/lib/artifacts/RequestHashStorage/index.ts, packages/smart-contracts/src/lib/artifacts/RequestHashSubmitter/index.ts
Just signed the unsigned commits from branch refactor/contract-setup-compression
=> refactor: contract setup compression fix

packages/currency/src/aggregators/goerli.json, packages/currency/src/erc20/networks/goerli.ts, packages/payment-detection/src/erc20/address-based.ts, packages/payment-detection/test/any/any-to-erc20-proxy-contract.test.ts, packages/payment-detection/test/erc20/address-based.test.ts, packages/payment-detection/test/erc20/fee-proxy-contract.test.ts, packages/payment-detection/test/erc20/proxy-contract.test.ts, packages/payment-detection/test/erc777/mocks.ts, packages/payment-detection/test/erc777/superfluid-retriever.test.ts, packages/payment-detection/test/eth/info-retriever.test.ts, packages/payment-detection/test/eth/input-data.test.ts, packages/payment-detection/test/provider.test.ts, packages/payment-processor/src/payment/utils.ts, packages/payment-processor/test/payment/utils.test.ts, packages/smart-contracts/scripts-create2/compute-one-address.ts, packages/smart-contracts/scripts-create2/contract-setup/setupETHConversionProxy.ts, packages/smart-contracts/scripts-create2/contract-setup/setups.ts, packages/smart-contracts/scripts-create2/deploy.ts, packages/smart-contracts/scripts-create2/utils.ts, packages/smart-contracts/scripts-create2/verify.ts, packages/smart-contracts/scripts/conversion-proxy.ts, packages/smart-contracts/scripts/deploy-payments.ts, packages/smart-contracts/scripts/test-deploy_chainlink_contract.ts, packages/smart-contracts/src/contracts/interfaces/IERC20ConversionProxy.sol, packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20EscrowToPay/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20SwapToPay/index.ts, packages/smart-contracts/src/lib/artifacts/EthConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumFeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumProxy/index.ts
=> feat: goerli payment

packages/advanced-logic/src/extensions/payment-network/erc20/address-based.ts, packages/advanced-logic/src/extensions/payment-network/erc20/fee-proxy-contract.ts, packages/advanced-logic/src/extensions/payment-network/erc20/proxy-contract.ts, packages/advanced-logic/src/extensions/payment-network/erc777/stream.ts, packages/advanced-logic/src/extensions/payment-network/ethereum/fee-proxy-contract.ts, packages/advanced-logic/src/extensions/payment-network/ethereum/input-data.ts
Add goerli support in payment-network
=> feat: add goerli support (advanced-logic)

packages/payment-processor/README.md, packages/payment-processor/src/payment/utils.ts, packages/payment-processor/test/payment/any-to-erc20-proxy.test.ts, packages/payment-processor/test/payment/encoder-approval.test.ts
Tests cannot be run twice without restart Ganache, and then, deploy again smart contracts.
Solution: reset approvals for the 2 tests, using a new function in utils.
Also, update README regarding tests, preventing people being working on smart-contracts before to get weird error because of the Network.
Modifications impact only on tests.
=> fix(payment-processor): add reset approvals to run twice tests

packages/payment-processor/src/payment/encoder-payment.ts, packages/payment-processor/src/payment/erc777-stream.ts, packages/payment-processor/test/payment/encoder-payment.test.ts, packages/payment-processor/test/payment/erc777-stream.test.ts
to follow the generic separation of the encoding of SuperFluid payment transactions done by API back-end from the signing done by front-end.
=> feat: add prepare and encode functions for SuperFluid

packages/advanced-logic/src/extensions/payment-network/erc777/stream.ts, packages/advanced-logic/test/extensions/payment-network/erc777/stream.test.ts, packages/advanced-logic/test/utils/payment-network/erc777/stream-create-data-generator.ts, packages/types/src/extensions/pn-any-stream-reference-based-types.ts, packages/types/src/utils.ts
This PR manages the creation of subsequent requests. 
The parameters for a subsequent request are:
- The `requestId` of the master request,
- The `requestId` of the previous request,
- The rank of the request in the series.
[Miro board associated](https://miro.com/app/board/uXjVOgVrEzY=/)
_Terminology:_
**master request**: first request of a series.
**subsequent request**: other requests of a series.
=> feat: sf advanced logic subsequent request

packages/payment-processor/test/payment/erc20-batch-proxy.test.ts, packages/payment-processor/test/payment/erc20-escrow-payment.test.ts, packages/payment-processor/test/payment/erc20.test.ts, packages/payment-processor/test/payment/eth-input-data.test.ts, packages/payment-processor/test/payment/swap-erc20-fee-proxy.test.ts
- revoke approvals for two old tests
- use .equalTo instead of .eq -> the tests were not working (correct one test also)
=> fix(payment-processor): within tests - revoke some approvals and use equalTo instead of eq

packages/payment-detection/src/erc777/superfluid-retriever.ts, packages/payment-detection/src/index.ts, packages/payment-detection/test/erc777/superfluid-retriever.test.ts, packages/types/src/payment-types.ts
Adding stream event names to streaming event parameters in the balance object.
The reason for this is that we need to be able to detect stream specific events like start and stop stream in portal for sending notifications and knowing when to stop updating the balance.
=> feat: add streamEventName to streaming event parameters

packages/payment-processor/src/payment/index.ts, packages/payment-processor/test/payment/encoder.test.ts
Transaction builder now always returns both approval and payment, without checking for allowance
=> feat: always return approval and payment transactions

packages/payment-detection/src/erc777/superfluid-retriever.ts
An error occurred in the following situation:
-  No payment events associated to the request
-  Untagged events associated to the stream (`payerAddress`, `payeeAddress`, `paymentCurrency`)
=> fix: superfluid balance error

packages/docs/docs/guides/1-first-request.md, packages/docs/docs/guides/3-Portal-API/1-create-and-share-request.md
I have updated URL used because it was confusing for our community users on Discord.
Request Create and Pay are not maintained anymore because they have been replaced by Request Finance.
=> fix: updating URL to RF

packages/payment-processor/src/payment/erc777-stream.ts
Add the possibility to calculate a user balance at certain time.
Useful for superfluid invoices in order to take into account incoming and ougoing streams.
[Asana task](https://app.asana.com/0/1202922067864171/1203022940884256)
=> feat: erc777 balance computation

packages/payment-detection/src/near/near-conversion-detector.ts, packages/payment-detection/test/near/near-native-conversion.test.ts
The NEAR contracts for conversion have been deployed, this PR updates their addresses for payment-detection.
=> fix: NEAR contracts addresses for conversion-native

packages/currency/src/conversion-aggregators.ts, packages/currency/src/currencyManager.ts, packages/currency/src/index.ts, packages/currency/test/chainlink-path-aggregators.test.ts, packages/toolbox/src/chainlinkConversionPathTools.ts, packages/toolbox/src/commands/chainlink/addAggregators.ts
There were references to Chainlink where we support other aggregation providers (Flux Oracles).
=> chore: replaced references to chainlink with aggregators

packages/currency/src/index.ts, packages/currency/test/chainlink-path-aggregators.test.ts, packages/toolbox/src/commands/chainlink/aggregatorsUtils.ts
AggregatorsMap is used by CurrencyManager constructor, so it should be exported.
=> chore(currency): export AggregatorsMap

packages/data-access/src/data-access.ts, packages/data-access/test/data-access.test.ts, packages/integration-test/test/native-token.test.ts, packages/integration-test/test/node-client.test.ts, packages/integration-test/test/scheduled/btc-test-data.ts, packages/integration-test/test/scheduled/escrow-detector.test.ts, packages/integration-test/test/scheduled/native-token.test.ts, packages/payment-detection/src/index.ts, packages/payment-detection/src/payment-network-factory.ts, packages/payment-detection/test/near/near-native-conversion.test.ts, packages/payment-detection/test/near/near-native.test.ts, packages/payment-detection/test/payment-network-factory.test.ts, packages/request-client.js/src/api/request-network.ts, packages/request-client.js/src/http-request-network.ts, packages/request-client.js/src/index.ts, packages/request-client.js/test/index.test.ts
The PaymentNetworkFactory was used as a set of static methods. I refactored it to be able to pass common dependencies in the constructor, like in the rest of the codebase.
This is in preparation for additional properties available for Payment Detection customization, like Subgraph URLs.
The idea is to be able to pass the configuration to the request client directly
=> refactor: payment network factory

packages/advanced-logic/src/extensions/payment-network/any-to-near.ts, packages/advanced-logic/src/extensions/payment-network/near-native.ts, packages/advanced-logic/test/extensions/payment-network/any-to-near.test.ts, packages/advanced-logic/test/extensions/payment-network/native-token.test.ts, packages/currency/src/conversion-aggregators.ts, packages/currency/src/currency-utils.ts, packages/payment-detection/src/eth/multichainExplorerApiProvider.ts, packages/payment-detection/src/near/near-conversion-detector.ts, packages/payment-detection/src/near/near-detector.ts, packages/payment-detection/src/near/retrievers/near-info-retriever.ts, packages/payment-detection/src/payment-network-factory.ts, packages/payment-detection/test/near/near-native-conversion.test.ts, packages/payment-detection/test/near/near-native.test.ts, packages/payment-processor/src/payment/utils-near.ts
This is a first temporary step towards replacing all the mistaken mentions of `aurora`.
This step is non-breaking and does not change the way we create or store requests.
It only focuses on testnet.
Target design after the whole change:
- Bump the request-logic version, and the concerned extension versions. These versions will only support `near` and `near-testnet`
- Keep supporting `aurora` and `aurora-testnet` for earlier versions of the extensions and request-logic
- The support for `aurora` and `aurora-testnet` should impact a small portion of the code, where we read the storage layer.
=> chore: support 'near-testnet' aside 'aurora-testnet'

packages/advanced-logic/test/extensions/payment-network/native-token.test.ts, packages/currency/src/currencyManager.ts, packages/currency/src/native.ts, packages/currency/test/currencyManager.test.ts
need new native token declared on new chain to be able to test the integration in currency-api and then from end to end
=> chore: adding tNEAR for near-testnet

packages/payment-detection/test/near/near-native.test.ts
* Adapt to the subgraph timestamp fix
=> fix: NEAR native timestamp precision

packages/types/src/extension-types.ts
fixup for https://github.com/RequestNetwork/requestNetwork/pull/950
=> fix: IPaymentNetworkState better typing

packages/currency/src/erc20/networks/avalanche.ts, packages/currency/src/erc20/networks/index.ts, packages/toolbox/src/commands/chainlink/aggregatorsUtils.ts
Adds a few Avalanche ERC20 as Currency Manager defaults.
Support the Avalanche network for the aggregators toolbox.
=> chore: default Avalanche currencies and aggregation util

packages/payment-processor/src/payment/erc20-escrow-payment.ts, packages/payment-processor/test/payment/erc20-escrow-payment.test.ts
There was no way to set the approval amount for escrow transaction. This fixes it.
I'm finishing a PR on the transaction-builder on portal where the approval amount can be defined. It's better if it also applies to escrow for consistency
=> feat: approval amount for escrow

packages/payment-detection/src/payment-network-factory.ts, packages/request-client.js/src/api/request-network.ts, packages/request-client.js/test/data-test.ts, packages/request-client.js/test/declarative-payments.test.ts, packages/request-client.js/test/index.test.ts
This [previous change](https://github.com/RequestNetwork/requestNetwork/pull/950) broke the support for conversion payment networks with payment chain checks. The root cause of the issue actually belongs to the `request-client.js` library: the conversion requests were handled poorly from day 1.
Includes:
- fix: support any-to-native
- chore: light restructure of `request-clients.js` test file, which is huge (deserves deeper restructuring)
=> fix: request-client should support conversion and network checks

packages/toolbox/src/commands/chainlink/addAggregator.ts, packages/toolbox/src/commands/chainlink/aggregatorsUtils.ts
Add an (optional) option to pass names instead of addresses
Doc: https://www.notion.so/request/Configure-conversion-aggregators-035c8bdb4d714590b97f96edb71bc28b#e6da9c3660a24053abfcf7f307f0b67f
Usage: 
```bash
export PRIVATE_KEY=...
yarn request-toolbox addAggregator goerli --input USDC --output USD --list invoicing --dryRun
yarn request-toolbox addAggregator goerli --input 0x... --output 0x775eb53d00dd0acd3ec1696472105d579b9b386b --aggregator 0x... --list invoicing --dryRun
```
=> feat(toolbox): add aggregators by name

packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/index.ts, packages/toolbox/src/commands/chainlink/contractUtils.ts
On Fantom and Matic, we have two versions of the chainlinkConversionPath contract.
Each of them are used by different contracts.
However the toolbox only updates the latest version of the chailinkConverPath contract. 
This aims to update all versions, this way we're sure that the new aggregators that we add are available on all versions.
=> fix: update all chainlink conversion path version

packages/payment-processor/src/payment/erc777-stream.ts
Add the Request prefix to superfluid one-off payments. (Same as streams)
=> fix: add prefix to one off payment request

packages/ethereum-storage/src/ethereum-storage-ethers.ts, packages/ethereum-storage/src/ethereum-storage.ts, packages/ethereum-storage/src/ethereum-tx-submitter.ts, packages/ethereum-storage/src/gas-fee-definer.ts, packages/ethereum-storage/src/gas-price-definer.ts, packages/ethereum-storage/src/smart-contract-manager.ts, packages/request-node/src/config.ts, packages/request-node/src/storageUtils.ts
This PR adds a new configuration to the request node:
- `argv.gasPriceMin`
- `process.env.GAS_PRICE_MIN`
This defaults to 1gwei, as we noticed by trial and error that most RPC nodes do not accept tx with a lower gas price (however we cannot find official spec to support this claim).
Typical errors from RPCs are:
> Error: FeeTooLow, EffectivePriorityFeePerGas too low 586749412 < 1000000000, BaseFee: 7
=> feat(ethereum-storage): add minimum gas price option

README.md, packages/payment-detection/README.md, packages/payment-detection/test/eth/info-retriever.test.ts
Fixes #1029
- Add `DISABLE_API_TESTS` env var. When set, disable tests that require API keys.
- Detect `CIRCLE_PR_NUMBER` env var and disable API tests if found. `CIRCLE_PR_NUMBER` indicates that PR originates from an external fork and thus cannot access secret API keys
- Failing CI tests are a major pain point for external contributors right now.
- This is a "bandaid fix". The underlying problem is that API-based checks should run nightly and unit tests should use mocks. See #1031.
* `CIRCLE_PR_NUMBER` is recommended by the Circle Blog: https://circleci.com/blog/managing-secrets-when-you-have-pull-requests-from-outside-contributors/
* `CIRCLE_PR_NUMBER` is **only** defined on PRs from external forks and shouldn't have any effect on PRs from internal branches.
* `CIRCLE_PR_NUMBER` is just …
=> fix: ci fails on prs from external forks

packages/smart-contracts/test/contracts/ChainlinkConversionPath.test.ts
Fixes #1037 
- Add `before` that resets the aggregator entries on the `ChainlinkConversionPath` contract to `0x000...`
=> fix(smart-contracts): subsequent runs fail

packages/ethereum-storage/src/ethereum-tx-submitter.ts, packages/smart-contracts/scripts-create2/contract-setup/adminTasks.ts, packages/smart-contracts/scripts-create2/xdeployer.ts, packages/utils/src/providers.ts
Small refacto to regroup logic related to eip1559 compliance
[Asana task](https://app.asana.com/0/1203350802794948/1203600402430065)
=> chore: add utility function to check eip1559 compliance

.circleci/config.yml, packages/payment-processor/src/payment/encoder-approval.ts, packages/payment-processor/test/payment/any-to-eth-proxy.test.ts, packages/payment-processor/test/payment/encoder-payment.test.ts, packages/payment-processor/test/payment/encoder.test.ts, packages/payment-processor/test/payment/erc777-stream.test.ts, packages/payment-processor/test/payment/eth-batch-proxy.test.ts, packages/payment-processor/test/payment/eth-fee-proxy.test.ts, packages/payment-processor/test/payment/eth-input-data.test.ts, packages/payment-processor/test/payment/eth-proxy.test.ts, packages/smart-contracts/hardhat.config.ts, packages/smart-contracts/package.json, packages/smart-contracts/test/contracts/BatchConversionPayments.test.ts, packages/smart-contracts/test/contracts/ERC20SwapToConversion.test.ts, packages/smart-contracts/test/contracts/ERC20SwapToPay.test.ts, packages/smart-contracts/test/contracts/EthConversionProxy.test.ts, packages/utils/package.json, packages/utils/src/estimate-gas-fees.ts, packages/utils/test/estimate-gas-fee.test.ts, yarn.lock
Replace the hardhat-ganache plugin by hardhat:
- Improve smart contract debugging
- Enable better configuration of the chain
- Enable eip1559 calls
Update the eip159 lib and add tests for it.
=> feat: replace hardhat ganache

packages/ethereum-storage/README.md, packages/request-node/README.md, packages/toolbox/src/commands/transaction/utils.ts, packages/utils/src/providers.ts
This adds support for the `ALCHEMY_API_KEY` environment variable in the toolbox's scripts.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204053766699980
=> chore(toolbox): add support for Alchemy

packages/request-client.js/src/api/request-network.ts, packages/types/src/client-types.ts
The refresh is useful when you want to use the request directly, but in a scenario where you will work with it asynchronously, it can cause instability
=> feat(request-client): add option to skip refresh

packages/payment-detection/src/payment-network-factory.ts, packages/payment-detection/src/thegraph/client.ts, packages/payment-detection/test/near/near-native.test.ts, packages/request-client.js/test/declarative-payments.test.ts
Main:
fix: PaymentNetworkFactory default subraph getter supports NEAR
Secondary:
chore: test declarative events in NEAR native payment detector
=> fix: default getTheGraphClient accounts for Near

packages/payment-processor/src/index.ts, packages/payment-processor/src/payment/erc20-fee-proxy.ts, packages/payment-processor/src/payment/index.ts, packages/payment-processor/src/payment/near-fungible.ts, packages/payment-processor/src/payment/swap-any-to-erc20.ts, packages/payment-processor/src/payment/swap-erc20-fee-proxy.ts, packages/payment-processor/src/payment/utils-near.ts, packages/payment-processor/src/payment/utils.ts, packages/payment-processor/test/payment/any-to-near.test.ts, packages/payment-processor/test/payment/erc20-fee-proxy-near.test.ts, packages/payment-processor/test/payment/index.test.ts, packages/smart-contracts/src/lib/artifacts/ERC20FeeProxy/index.ts
feat: `payment-processor` method for paying an ERC20FeeProxy request on Near, by sending fungible tokens to a proxy contract.
chore: deployment address for mainnet.
=> feat: processor for ERC20FeeProxy on Near

packages/integration-test/test/node-client.test.ts, packages/request-node/src/request/confirmedTransactionStore.ts, packages/request-node/src/request/persistTransaction.ts, packages/thegraph-data-access/src/data-access.ts, packages/utils/src/retry.ts
This PR:
- removes `it.only` in integration tests that was introduced by mistake in https://github.com/RequestNetwork/requestNetwork/pull/977
- and fixes integrations tests that silently boke in https://github.com/RequestNetwork/requestNetwork/pull/1078
=> fix(integration-tests): unskip tests

packages/ethereum-storage/src/ethereum-storage-ethers.ts, packages/types/src/storage-types.ts
For debug purposes, it would be nice to have access to the nonce of the transaction that persisted the request.
=> chore(ethereum-storage-ethers): return nonce in append meta

packages/advanced-logic/src/extensions/payment-network/erc20/transferable-receivable.ts, packages/payment-detection/src/erc20/transferable-receivable.ts, packages/payment-processor/package.json, packages/payment-processor/src/payment/erc20-transferable-receivable.ts, packages/payment-processor/test/payment/erc20-transferable-receivable.test.ts, packages/smart-contracts/scripts/test-deploy-erc20-transferable-receivable.ts, packages/smart-contracts/src/contracts/ERC20TransferableReceivable.sol, packages/smart-contracts/src/lib/artifacts/ERC20TransferableReceivable/0.2.0.json, packages/smart-contracts/src/lib/artifacts/ERC20TransferableReceivable/index.ts, packages/smart-contracts/test/contracts/ERC20TransferableReceivable.test.ts
This pull request aims to cut gas costs on the ERC20TransferableReceivable contract. The changes proposed are based on the findings of a gas profiler and include the following optimizations:
- Remove the ERC721Enumerable functionality since it is not critical to the final product. Request Finance already knows all of a user's invoices and can map each one to their respective receivables. Previously we only used this to power our demo experience on the Huma dApp.
- Stop using ERC721URIStorage as a glorified storage field for requestID. This is a significant waste of gas since strings need to be processed and stored. Instead, revert to the base ERC721 URI storage and create a new field requestID in the ReceivableInfo struct.
- This still allows for us to upgrade the receivables contract …
=> feat: ERC20TransferableReceivable contract gas optimizations

packages/advanced-logic/src/extensions/payment-network/address-based.ts, packages/currency/src/currencyManager.ts, packages/currency/src/types.ts, packages/currency/test/currencyManager.test.ts, packages/request-client.js/src/api/request-network.ts
The purpose of this change is to allow users to provide a custom `validateCurrency` & `validateAddress` method for currency which not supported by the library.
Updated: 
- method access as public
- updated usage in the request-client
=> chore: make validate currency as public method

packages/ethereum-storage/src/gas-fee-definer.ts, packages/smart-contracts/scripts-create2/contract-setup/adminTasks.ts, packages/smart-contracts/scripts-create2/xdeployer.ts, packages/utils/src/estimate-gas-fees.ts, packages/utils/test/estimate-gas-fee.test.ts
It can happen, rarely, that `@rainbow-me/fee-suggestions` fails to estimate gas fees, especially on chains other than Ethereum mainnet (related to https://github.com/rainbow-me/fee-suggestions/issues/23).
This PR catches,  logs, and handles those errors by returning an empty object, thus letting the RPC provider choose how to configure gas fee / gas price (either by using defaults for the EIP-1559 transaction fields or falling back to a legacy, non-EIP 1559, transaction).
=> fix(gas-fee): catch estimation errors

packages/payment-processor/src/payment/index.ts, packages/payment-processor/test/payment/index.test.ts
Hackers at ETHBarcelona 2023 were unable to use the `hasSufficientFunds()` function with `ETH_FEE_PROXY_CONTRACT` requests because of the following check:
https://github.com/RequestNetwork/requestNetwork/blob/master/packages/payment-processor/src/payment/index.ts#L206-L208
```
if (!paymentNetwork || !noConversionNetworks.includes(paymentNetwork)) {
throw new UnsupportedNetworkError(paymentNetwork);
}
```
Add `ETH_FEE_PROXY_CONTRACT` to `noConversionNetworks`
1. Are there any other payment networks that should be added?
=> fix: add ETH_FEE_PROXY_CONTRACT to noConversionNetworks

packages/currency/src/currencyManager.ts
Pass generic to `CurrencyDefinition` to avoid type casting with `as` upon usage.
=> chore(currency): add TMeta generic to getDefaultList

packages/request-logic/src/request-logic.ts, packages/request-logic/test/index.test.ts
=> refactor(request-logic): event emitter

.circleci/config.yml
Fix the graph node integration test, after the update of `@graphprotocol/graph-cli` in https://github.com/RequestNetwork/storage-subgraph/pull/4
=> ci: fix creation of storage subgraph

packages/payment-processor/package.json, yarn.lock
=> chore: Bump near-api-js to v2.1.4

packages/smart-contracts/scripts-create2/deploy-request-deployer.ts
https://github.com/RequestNetwork/requestNetwork/pull/1127#discussion_r1274537692
> [hardcoded address] should be a variable or should have a comment
* fix: replace the hardcoded address with `deployerAddress` var from hardhat runtime environment `hre`
=> fix: replace hardcoded address

packages/payment-processor/src/payment/settings.ts, packages/payment-processor/src/payment/swap-any-to-erc20.ts
Fixes #1144
Hi, a new contributor here!
Trying to fix the issue #1144
I've added an optional parameter `maxRateAge` in ~`ISwapSettings`~ `IConversionSettings`. It defaults to 0.
We can keep it required too, wdyt?
=> fix: remove hardcoded chainlink rate age (#1171)

packages/ethereum-storage/README.md, packages/ethereum-storage/scripts/init-ipfs.js, packages/request-node/README.md
Fixes #1083
Changed the READMEs to suggest using `requestnetwork/request-ipfs`.
- packages/ethereum-storage/README.md
- packages/request-node/README.md
Also, I didn't remove the `ipfs-init.js` script to keep things backward compatible.
=> docs: `request-ipfs` image for local node (#1083)

packages/payment-processor/src/payment/utils-near.ts
The NEAR-USDC storage check (and initiator) are not named according to the [standard](https://docs.near.org/develop/relevant-contracts/ft).
=> fix: storage check for USDC on Near is custom

packages/payment-processor/src/payment/utils-near.ts
#1180 is buggy, the custom `check_registration` method from Circle also comes with a different interface, returning a boolean.
=> fix: NEAR storage check is boolean

packages/ethereum-storage/package.json, packages/ethereum-storage/src/ethereum-tx-submitter.ts, packages/ethereum-storage/src/gas-fee-definer.ts, packages/ethereum-storage/test/gas-fee-definer.test.ts, packages/smart-contracts/package.json, packages/smart-contracts/scripts-create2/contract-setup/adminTasks.ts, packages/smart-contracts/scripts-create2/fee-suggestion.ts, packages/smart-contracts/scripts-create2/xdeployer.ts, packages/toolbox/src/commands/chainlink/contractUtils.ts, packages/types/src/fees-types.ts, packages/types/src/index.ts, packages/utils/package.json, packages/utils/src/estimate-gas-fees.ts, packages/utils/src/index.ts, packages/utils/src/normalize-gas-fees.ts
Remove `@rainbow-me/fee-suggestions` from the utils package, to reduce dependencies in other packages.
=> refactor: estimate gas fee

packages/toolbox/src/commands/chainlink/addAggregator.ts
This is a follow-up to @olivier7delf 's comment ([here](https://github.com/RequestNetwork/requestNetwork/pull/1134#discussion_r1297086909)) on https://github.com/RequestNetwork/requestNetwork/pull/1134
This makes the args immutable (replaced `let` by `const`) and variable manipulations a bit clearer.
=> refactor(toolbox): addAggregator immutable args

packages/integration-test/test/node-client.test.ts
* Update existing test so that it also cancels a request after it is paid
* Renamed test to `can create ETH requests and pay with ETH Fee proxy and cancel after paid`
Request Finance user asked to void a paid invoice because they want to edit their description. @kevindavee asked: Is it possible to cancel a request that has already been paid?
Yes. it is possible to cancel a request that has already been paid. :white_check_mark: 
<details>
<summary>The returned request data, after cancel, shows `state` is `canceled` and the balance remains `1000`. (click to expand)
</summary>
```json
{
"_events": {},
"_eventsCount": 0,
"currency": "ETH-private-private",
"expectedAmount": "1000",
"payee": {
"type": "ethereumAddress",
"value": "0x627306090abab3a6e1400e9345bc60c78a8bef57"
},
"payer": {
"type": …
```
=> chore: test cancel after paid

yarn.lock
Adding new dependencies in the `packages/utils` directory is impossible. If you navigate to `cd packages/utils` and try to install a new package, for instance `yarn add eccrypto-js`, you will face the issue:
```
error An unexpected error occurred: "expected workspace package to exist for \"string-width\"".
```
The issue is described here: https://github.com/yarnpkg/yarn/issues/7807
The solution was to run
```sh
npx yarn-deduplicate --packages string-width
```
I chose to only run the fix for this specific package and not all packages in the lock file as described in Yarn's GitHub comment (I tried it at first, but this led to more issues with the build).
=> chore: yarn-deduplicate for string-width

packages/utils/test/crypto/data/crypto-browser.ts, packages/utils/test/crypto/data/crypto-native.ts
We are not using `eccrypto-js` in the end (see https://github.com/RequestNetwork/requestNetwork/pull/1229) so it might be confusing to keep this in the comments.
=> docs: remove reference to eccrypto-js

packages/data-access/src/combined-data-access.ts, packages/data-access/src/in-memory-indexer.ts, packages/request-client.js/test/index.test.ts, packages/thegraph-data-access/src/data-access.ts
This metadata is used for balance events, and use class methods in CombinedDataAccess so that they can be overriden
=> fix(storage): in memory indexer metadata, use methods

.circleci/config.yml
the format & lint takes about a minute. It shouldn't be part of the `build` stage, but in a separate `lint` stage (together with package.json lint)
=> ci: move lint out of build

packages/currency/src/chains/evm/index.ts, packages/currency/src/native.ts, packages/payment-detection/src/eth/multichainExplorerApiProvider.ts, packages/smart-contracts/README.md, packages/smart-contracts/hardhat.config.ts, packages/smart-contracts/src/lib/artifacts/BatchConversionPayments/index.ts, packages/smart-contracts/src/lib/artifacts/BatchPayments/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20FeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumFeeProxy/index.ts, packages/types/src/currency-types.ts, packages/utils/src/providers.ts
We rely on that all network names are in lowercase in Invoicing, with the mixed letters the UI could not match the currency chain with the chainList from currency API.
Also added the batch contract address from zksync testnet.
=> fix: zksync networks names to lowercase

packages/payment-detection/src/index.ts, packages/payment-detection/src/thegraph/client.ts, packages/payment-detection/src/thegraph/conversion-info-retriever.ts, packages/payment-detection/src/thegraph/info-retriever.ts, packages/payment-detection/src/thegraph/queries/GetPaymentsAndEscrowState.graphql, packages/payment-detection/src/thegraph/queries/graphql.config.yml, packages/payment-detection/src/thegraph/queries/near/graphql.config.yml, packages/payment-detection/src/thegraph/queries/superfluid/graphql.config.yml, packages/payment-detection/test/any/any-to-erc20-proxy-contract.test.ts, packages/payment-detection/test/any/any-to-eth.test.ts, packages/payment-detection/test/erc20/proxy-contract.test.ts, packages/payment-detection/test/eth/input-data.test.ts
supersedes https://github.com/RequestNetwork/requestNetwork/pull/1253
When using TheGraph decentralized network, different GQL queries can target different indexers. For consistency, we can ask to target only indexers that have processed specific blocks using a block filter.
For more info, see [here](https://thegraph.com/docs/en/cookbook/upgrading-a-subgraph/) or [here](https://thegraph.com/blog/how-to-migrate-ethereum-subgraph/), look for `number_gte` in these pages.
- Added a new `minIndexedBlock` option to TheGraph client in order to handle this
=> feat(payment-detection): add minIndexedBlock option for TheGraph

packages/payment-detection/src/thegraph/client.ts, packages/payment-detection/src/thegraph/conversion-info-retriever.ts, packages/payment-detection/src/thegraph/info-retriever.ts, packages/payment-detection/src/thegraph/queries/GetPaymentsAndEscrowState.graphql
This is a fixup for https://github.com/RequestNetwork/requestNetwork/pull/1262 and https://github.com/RequestNetwork/requestNetwork/pull/1265
When using TheGraph decentralized network, different GQL queries can target different indexers. For consistency, we can ask to target only indexers that have processed specific blocks using a block filter.
For more info, see [here](https://thegraph.com/docs/en/cookbook/upgrading-a-subgraph/) or [here](https://thegraph.com/blog/how-to-migrate-ethereum-subgraph/), look for `number_gte` in these pages.
When we don't have the data for which minimum block an indexer should have processed, we must set a default value. After several unsuccessful tries, here is what I've found regarding generating a default value that works with both a normal TheGraph Node …
=> fix(payment-detection): differenciate decentralized network case

packages/data-access/README.md, packages/integration-test/test/scheduled/native-token.test.ts, packages/payment-processor/src/payment/batch-conversion-proxy.ts, packages/request-node/README.md, packages/request-node/package.json, packages/request-node/src/config.ts, packages/request-node/src/dataAccess.ts, packages/request-node/src/dataStorage.ts, packages/request-node/src/request/confirmedTransactionStore.ts, packages/request-node/src/request/getConfirmedTransactionHandler.ts, packages/request-node/src/request/persistTransaction.ts, packages/request-node/src/requestNode.ts, packages/request-node/src/server.ts, packages/request-node/test/getChannelsByTopic.test.ts, packages/request-node/test/getConfirmedTransaction.test.ts, packages/request-node/test/getTransactionsByChannelId.test.ts, packages/request-node/test/persistTransaction.test.ts, packages/smart-contracts/deploy/utils-zk.ts, packages/smart-contracts/test/contracts/BatchNoConversionErc20Payments.test.ts, packages/smart-contracts/test/contracts/BatchNoConversionEthPayments.test.ts, packages/thegraph-data-access/src/queries.ts, packages/thegraph-data-access/src/subgraph-client.ts, yarn.lock
Resolves #1287
Requires https://github.com/RequestNetwork/storage-subgraph/pull/13
This changes removes the handling of failed transactions. I think this is acceptable, since there is a relatively short timeout on confirmation, and failures aren't very common. Please feel free to challenge this.
=> feat(request-node): use subgraph for confirmation

packages/thegraph-data-access/src/queries.ts, packages/thegraph-data-access/src/subgraph-client.ts
Use https://github.com/RequestNetwork/storage-subgraph/pull/14 to optimize queries to the Subgraph. Resolves #1199
=> fix(thegraph): optimize getTransactionsByTopics

packages/currency/src/erc20/chains/index.ts, packages/toolbox/src/commands/chainlink/contractUtils.ts, packages/utils/src/providers.ts
- adding a default RPC for sepolia
- fixing double transactions, when contract versions have the same address (this is a hack so that requests can have PN version 2.0 or 2.1)
- add sepolia to default currency list
=> chore(toolbox): sepolia and fix double transaction

packages/request-client.js/src/api/request.ts
`declareSentPayment` and `declareSentRefund` can accept `txHash` and `network` incase the payment/refund is made by declaring a transaction link as the proof. We just need to expose it to the `request-client`
=> feat(request-client): expose txHash and network for declareSent

packages/ethereum-storage/src/ethereum-tx-submitter.ts, packages/ethereum-storage/src/gas-fee-definer.ts, packages/utils/src/normalize-gas-fees.ts, packages/utils/test/normalize-gas-fees.test.ts
This PR introduces two new options to the `EthereumTransactionSubmitter`:
- `gasPriceMax`: this parameter can be used to protect against gas price spikes and adds an upper threshold
- `gasPriceMultiplier`: this parameter can be used to add a margin to the computed gas fee
=> feat(ethereum-storage): gas fee multiplier & max gas fee

packages/smart-contracts/src/lib/artifacts/BatchPayments/index.ts
fixes #1303 
Removes the entries from BatchPayments/index.ts for both prod and test zksync. These were errornously added with #1261
=> fix: remove zksync from BatchPayments

packages/request-node/src/config.ts, packages/request-node/src/dataAccess.ts
* fix: add `gasPriceMax` and `gasPriceMultiplier` to the Request Node config
(Copied with minor edits from https://github.com/RequestNetwork/marble/pull/141, written by @alexandre-abrioux)
This PR was made possible thanks to https://github.com/RequestNetwork/requestNetwork/pull/1318, and should fix the following issue that we get from time to time while persisting transactions on-chain:
> FeeTooLow, EffectivePriorityFeePerGas too low 806006831 < 1000000000, BaseFee: 23667261698
There is also more info on why the `gasPriceMultiplier` was introduced in the protocol https://github.com/RequestNetwork/requestNetwork/pull/1318#discussion_r1447581135.
When submitting a transaction with the following EIP-1559 parameters:
```
2,000,000,000 wei (= 2 Gwei)  for the maxPriorityFeePerGas (given to …
```
=> fix: add `gasPriceMax` and `gasPriceMultiplier` to the Request Node config

packages/smart-contracts/scripts-create2/contract-setup/execute-contract-method.ts, packages/smart-contracts/src/lib/artifacts/Admin/index.ts
Add Safes for RN administration on supported chains.
TBD:
- Finalize the list of admins 
- Update the signature threshol to 3
- Transfer the ownership of the contracts to the Safes
By default, if an update on a specific network is not possible via Safe, fallback to EOA.
=> chore: add safe admins

packages/advanced-logic/package.json, packages/currency/package.json, packages/data-access/package.json, packages/data-format/package.json, packages/epk-decryption/package.json, packages/epk-signature/package.json, packages/ethereum-storage/package.json, packages/integration-test/package.json, packages/multi-format/package.json, packages/payment-processor/package.json, packages/request-client.js/package.json, packages/request-logic/package.json, packages/request-node/package.json, packages/smart-contracts/package.json, packages/thegraph-data-access/package.json, packages/toolbox/package.json, packages/transaction-manager/package.json, packages/types/package.json, packages/usage-examples/package.json, packages/utils/package.json, packages/web3-signature/package.json, yarn.lock
This fixes the issue introduced by #1328 , when running `next-release` as part of the CI.
Partial view of the problem:
```
> @requestnetwork/data-format:clean
$ shx rm -rf dist tsconfig.tsbuildinfo tsconfig.build.tsbuildinfo
rm: no such file or directory: tsconfig.tsbuildinfo
```
=> chore(cd): fix clean script for cd

lerna.json
* Remove `useWorkspaces: true` from `lerna.json`
```
lerna ERR! ECONFIGWORKSPACES The "useWorkspaces" option has been removed. By default lerna will resolve your packages using your package manager's workspaces configuration. Alternatively, you can manually provide a list of package globs to be used instead via the "packages" option in lerna.json.
```
=> fix: lerna publish error

packages/ethereum-storage/package.json, packages/ethereum-storage/src/ipfs-manager.ts, packages/ethereum-storage/test/ipfs-manager.test.ts, yarn.lock
Resolves https://github.com/advisories/GHSA-mxhp-79qh-mcx6 (not spotted by Github Security vulnerabilities, but visible in GCP docker registry scanner)
`ipfs-unixfs@6.0.7` > `protobufjs@6.11.4` > `taffydb@2.6.2`
We cannot upgrade ipfs-unixfs easily due to a breaking change to drop CJS support. 
`ipfs-unixfs` was only used to read IPFS content, which we don't need anymore, since the indexing is done by the Subgraph
=> chore(security): remove ipfs-unixfs

packages/payment-processor/src/payment/index.ts, packages/payment-processor/test/payment/index.test.ts, packages/usage-examples/src/pay-erc20-request.ts, packages/usage-examples/src/pay-eth-request.ts
The method `isSolvent` was broken.
```ts
const needsGas =
!(provider as any)?.provider?.safe?.safeAddress &&
(provider as any)?.provider?.wc?._peerMeta?.name,
);
```
This is not working as intended anymore, and these info are no longer on the `provider` object.
I propose instead to pass a `needsGas` value - which is true by default. It should be to the client to decide whether he wants to check for gas fees or not, the protocol can't handle the situation for every wallet.
=> fix: isSolvent

packages/integration-test/test/scheduled/native-token.test.ts, packages/payment-detection/package.json, packages/payment-detection/src/thegraph/client.ts, packages/payment-detection/src/thegraph/info-retriever.ts, packages/payment-detection/src/thegraph/superfluid.ts, packages/payment-detection/src/utils.ts, packages/payment-detection/test/utils.test.ts, packages/toolbox/package.json, packages/types/src/payment-types.ts, yarn.lock
This PR removes yet another superfluous dependency that causes security warnings and increases package size: lodash.
=> feat: remove lodash

packages/advanced-logic/src/extensions/payment-network/any-to-erc20-proxy.ts, packages/advanced-logic/src/extensions/payment-network/any-to-eth-proxy.ts, packages/advanced-logic/src/extensions/payment-network/any-to-native.ts, packages/advanced-logic/test/extensions/payment-network/any-to-erc20-proxy.test.ts, packages/integration-test/test/scheduled/mocks.ts, packages/payment-detection/src/any-to-any-detector.ts, packages/payment-detection/src/any/any-to-erc20-proxy.ts, packages/payment-detection/src/declarative.ts, packages/payment-detection/src/erc20/fee-proxy-contract.ts, packages/payment-detection/src/fee-reference-based-detector.ts, packages/payment-detection/src/payment-detector-base.ts, packages/payment-detection/src/payment-network-factory.ts, packages/payment-detection/src/reference-based-detector.ts, packages/payment-detection/test/any/any-to-erc20-proxy-contract.test.ts, packages/request-client.js/src/api/request-network.ts, packages/types/src/advanced-logic-types.ts, packages/types/src/extensions/pn-any-to-erc20-types.ts, packages/types/src/extensions/pn-any-to-eth-types.ts, packages/types/src/payment-types.ts
Make payment network parameters strongly typed, and more precise:
```ts
await pnFactory
.createPaymentNetwork(
ExtensionTypes.PAYMENT_NETWORK_ID.ANY_TO_ERC20_PROXY,
RequestLogicTypes.CURRENCY.ERC20,
'mainnet',
)
//  strongly typed to ANY_TO_ERC20_PROXY Payment Network.
.createExtensionsDataForCreation({
// TS error because misses `acceptedTokens`
// TS error because `network` is not valid
network: "not a valid name"
}),
```
=> feat: improve payment network types

packages/payment-detection/src/thegraph/client.ts
This is a follow-up on https://github.com/RequestNetwork/requestNetwork/pull/1267, the decentralized gateway of TheGraph has changed its validation regarding accepted values on block filters. We need to change the default when no block filter is used.
| Block Filter                      | TheGraph Node                                             | TheGraph Gateway (decentralized)                                            |
|-----------------------------------|-----------------------------------------------------------|-----------------------------------------------------------------------------|
| `undefined`                         | ✅                                                         | ❌ `Invalid query: Failed to determine block constraints.`                     |
| `null` …
=> fix(payment-detection): default block filter on decentralized network

packages/request-client.js/src/api/request-network.ts, packages/request-logic/src/request-logic.ts
In theory, we can Pay a request before persisting it in the Request Network protocol.
In other words, we create a Request in memory without persisting it. Then, we prompt the end user to send payment against that request. Finally, we persist the request - so that it may serve as a receipt for the payment.
However, the existing SDK functions assume that the request is persisted immediately after being created.
This shortens the critical path for a user making a payment. This is especially desirable for payment apps - in which a payer wants to buy something. The workflow is driven by the _payer_ instead of the payee, so why make them wait for the request to be persisted before allowing them to send a payment?
* feat: public funcs for creating a request in memory without persisting
I traced …
=> feat: Pay before Persist experiment

packages/smart-contracts/scripts-create2/contract-setup/execute-contract-method.ts, packages/smart-contracts/src/lib/artifacts/BatchConversionPayments/index.ts
Deployment of the `BatchPaymentConversion` contract on core.
https://scan.coredao.org/address/0x02561967c48e87cfB079763F3BEf6424A5A166A7#transactions
=> feat: core batch payment

packages/currency/src/native.ts, packages/smart-contracts/src/lib/artifacts/Erc20ConversionProxy/index.ts
The native currency for base was missing. 
I updated the following contracts who were were not initialized:
- ChainlinkConversionPath
- EthConversionProxy
- Erc20ConversionProxy
- Batch
- SwapToPay
- SwapToConversion
See the latest transactions https://basescan.org/address/0x4e64c2d06d19d13061e62e291b2c4e9fe5679b93
=> fix: base deployment

packages/payment-detection/src/thegraph/client.ts
A bug was fixed in TheGraph Studio's interface, and we successfully transferred the Gnosis Chain subgraph. However, we're still unable to process the Ethereum one (similar issue).
=> chore(thegraph): fix xdai subgraph URL

packages/payment-processor/package.json, packages/payment-processor/src/payment/utils-near.ts, yarn.lock
Towards #1390 
* chore: update to near-api-js 4.0.2
For https://github.com/near/near-api-js/pull/1194 - to avoid the need to polyfill `http` and `https` in React Native environments. I'll be able to test it in https://github.com/RequestNetwork/expo-starter-request-network as soon as the `-next` version is released to NPM.
Using `npm link` I verified that this does indeed eliminate the need to polyfill `http` and `https` :+1:
=> chore: update to near-api-js 4.0.2

packages/payment-detection/src/thegraph/client.ts
Fixes #1413 
* Add `THE_GRAPH_STUDIO_URL_BASE`
=> fix: payments-subgraph URL on Base

packages/payment-detection/codegen-superfluid.yml, packages/payment-detection/src/thegraph/superfluid.ts
Fixes #1417 
* fix: superfulid subgraph url
=> fix: superfulid subgraph url

packages/smart-contracts/scripts-create2/utils.ts, packages/smart-contracts/src/lib/artifacts/ERC20TransferableReceivable/index.ts
Resolves #1416 
* ERC20TransferableReceivable on Sepolia Deployed and Verified :white_check_mark: 
https://sepolia.etherscan.io/address/0xB5E53C3d145Cbaa61C7028736A1fF0bC6817A4c5#code
<details><summary>Console Log</summary>
<p>
```console
mantisclone@mantisclone-Inspiron-7620:~/projects/requestNetwork/packages/smart-contracts$ yarn hardhat compute-contract-addresses --network sepolia
yarn run v1.22.19
$ /home/mantisclone/projects/requestNetwork/node_modules/.bin/hardhat compute-contract-addresses --network sepolia
Nothing to compile
No need to generate any newer typings.
ERC20TransferableReceivable         0xB5E53C3d145Cbaa61C7028736A1fF0bC6817A4c5
Done in 1.79s.
mantisclone@mantisclone-Inspiron-7620:~/projects/requestNetwork/packages/smart-contracts$ yarn hardhat …
```
=> chore: deploy ERC20TransferableReceivable to Sepolia

yarn.lock
* fix: yarn lock had ^4.0.2 while package.json had 4.0.2
=> fix: yarn lock had near-api-js ^4.0.2 while package.json had 4.0.2

packages/payment-detection/src/thegraph/queries/superfluid/graphql.config.yml, packages/payment-detection/src/thegraph/superfluid.ts, packages/payment-detection/test/thegraph/superfulid.test.ts
Fixes #1417
* fix: superfluid subgraph urls - 2nd attempt
=> fix: superfluid subgraph urls - 2nd attempt

packages/currency/src/erc20/chains/sepolia.ts
Fixed Invalid Decimal Places on `fUSDC` and `fUSDT` on sepolia. Initially it was `18` by according to smart contracts on sepolia it is `6` which can cause invalid `expectedAmount` if one parses units with these Decimals.
https://sepolia.etherscan.io/address/0xF046b3CA5ae2879c6bAcC4D42fAF363eE8379F78#readContract
https://sepolia.etherscan.io/address/0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238#readProxyContract
=> fix: invalid decimal places for fUSDT and fUSDC on sepolia
