README.md
Hi there :v:
Love the project !
Small adjustment on the README for all the yarn lover out there :)
=> Setup with yarn

src/servicesContracts.ts
- Added `InterfaceArtifact` type reference
- Use `.some` instead of `.forEach` since it [returns immediately when truthy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some)
=> refactor: add types + improve logic in servicesContracts

.gitignore, packages/requestNetwork.js/README.md, packages/requestNetwork.js/test/deploy.ts, packages/requestNetworkSmartContracts/README.md
Fix import for case-sensitive file systems
Update the Developing section of the doc
=> Fix import case sensitive

packages/requestNetworkSmartContracts/contracts/base/math/SafeMathInt.sol, packages/requestNetworkSmartContracts/contracts/test/SafeMathIntMock.sol, packages/requestNetworkSmartContracts/test/base/math/SafeMathInt-test.js
Fix issues reported in https://github.com/RequestNetwork/requestNetwork/issues/43
=> Prevent overflow in SafeMathInt

.circleci/config.yml, .dockerignore, Dockerfile
=> chore(CI): optimize docker build

.circleci/config.yml
Automates the release of `next` package versions.
Fix some dependencies to test deploy.
=> build: automate next version package releases

packages/smart-contracts/tsconfig.json
Remove the unused references in tsconfig file
https://requestnetwork.atlassian.net/browse/PROT-1062
=> chore: remove unused references in smart-contracts package

packages/advanced-logic/specs/payment-network-eth-input-data-0.1.0-DRAFT.md, packages/request-client.js/test/index.test.ts
=> docs: put "salt" as mandatory in the eth-input-data payment network

packages/integration-test/test/node-client.test.ts
The integration test wasn't testing for the declarative request parameters, which were actually wrong.
=> test(declarative): added test on declarative parameters

packages/smart-contracts/src/contracts/ERC20Proxy.sol
https://requestnetwork.atlassian.net/browse/PROT-1083
=> fix: add payable to the ERC20 proxy contract fallback

packages/advanced-logic/specs/payment-network-erc20-proxy-contract-0.1.0-DRAFT.md, packages/smart-contracts/artifacts/ERC20Proxy/0.1.0.json, packages/smart-contracts/artifacts/ERC20Proxy/artifacts.json
https://requestnetwork.atlassian.net/browse/PROT-1023
=> feat: deploy ERC20 proxy smart contract to Rinkeby

packages/advanced-logic/specs/payment-network-erc20-proxy-contract-0.1.0-DRAFT.md, packages/smart-contracts/artifacts/ERC20Proxy/artifacts.json
https://requestnetwork.atlassian.net/browse/PROT-1024
=> feat: deploy ERC20 proxy smart contract to mainnet

packages/request-client.js/test/index-encryption.html, packages/request-client.js/test/index-metamask.html, packages/request-client.js/test/index.html
=> docs: fix request-client.js examples

.circleci/config.yml
=> chore: Update ganache version for circle-ci

.github/workflows/auto-approve-dependabot.yml
Auto-approve dependabot PRs action.
First-step to auto-merge dependabot PRs.
=> chore: auto-approve dependabot PRs action

packages/payment-detection/package.json, packages/payment-processor/package.json, packages/request-client.js/package.json, packages/smart-contracts/package.json, packages/usage-examples/package.json, yarn.lock
Bump ethers version to fix broken Ethers API.
=> chore: bump ethers version to 4.0.45

packages/docs/package.json, yarn.lock
Upgrade docusaurus to the latest version. Fix some dependency issues.
=> Upgrade docusaurus

packages/docs/docs/guides/1-first-request.md, packages/docs/docs/guides/3-API/0-portal-intro.md, packages/docs/docs/guides/3-API/1-create-and-share-request.md, packages/docs/docs/guides/3-API/3-api-apps.md, packages/docs/docs/guides/3-API/4-api-encryption.md, packages/docs/docs/guides/4-request-payment/0-intro.md, packages/docs/docs/guides/4-request-payment/1-payment-page.md, packages/docs/docs/guides/4-request-payment/2-multisig.md, packages/docs/docs/guides/5-request-client/0-intro.md, packages/docs/docs/guides/5-request-client/1-payment-networks.md, packages/docs/docs/guides/5-request-client/2-erc20-payment-detection.md, packages/docs/docs/guides/5-request-client/3-eth-payment-detection.md, packages/docs/docs/guides/5-request-client/4-btc-payment-detection.md, packages/docs/docs/guides/5-request-client/5-encryption.md, packages/docs/docs/guides/6-hosting-a-node/0-intro.md, packages/docs/docs/guides/6-hosting-a-node/1-installation.md, packages/docs/docs/guides/6-hosting-a-node/2-local-node.md, packages/docs/docs/guides/7-protocol/0-intro.md, packages/docs/sidebars.js, yarn.lock
Some pages were not working anymore with recent changes.
=> Docs with sidebar fix

.circleci/config.yml
See lerna docs about prerelease: https://github.com/lerna/lerna/blob/master/commands/version/README.md#prerelease
=> fix: lerna prerelease

packages/docs/docs/guides/5-request-client/6-encryption.md
https://requestnetwork.atlassian.net/browse/PROT-
=> docs: Completed encryption introduction & disclaimer

packages/docs/docs/guides/8-glossary.md
Adding a glossary for the documentation that explains the basic terms of the Protocol and some terms about the ecosystem of Request
=> docs: Adding a glossary

packages/data-access/src/block.ts, packages/data-access/src/data-access.ts, packages/request-node/test/getTransactionsByChannelId.test.ts
=> fix: block parsing with encrypted transaction

.circleci/config.yml
Remove push-request-network-image CI job
=> chore: remove push-request-network-image CI job

packages/docs/package.json, yarn.lock
Upgrade docusaurus version to alpha.49 to fix build error.
=> build: upgrade docusaurus version

yarn.lock
=> fix: push yarn.lock modifications

packages/docs/docs/guides/5-request-client/1-payment-networks.md
- Simplify payment network guide
- Document how to add an ERC20
- Document the proxy smart contract addresses
=> docs: Refresh payment network explanations

packages/docs/docs/guides/3-Portal-API/2-payment-status.md, packages/docs/docs/guides/5-request-client/2-erc20-payment-detection.ts, packages/docs/docs/guides/5-request-client/3-eth-payment-detection.ts, packages/docs/docs/guides/5-request-client/4-btc-payment-detection.ts, packages/docs/docs/guides/5-request-client/5-declarative-payment-network.ts
=> docs: fix the documentation of the balance

packages/types/src/client-types.ts
=> fix: topic can be any not only string

packages/advanced-logic/src/extensions/payment-network/declarative.ts, packages/payment-detection/test/declarative.test.ts, packages/request-client.js/src/api/request.ts, packages/request-client.js/test/index.test.ts, packages/request-logic/test/unit/actions/create.test.ts, packages/types/src/extensions/pn-any-declarative-types.ts, packages/types/src/request-logic-types.ts, packages/utils/src/amount.ts, packages/utils/test/amount.test.ts
=> feat: amount are only number or string

packages/docs/docs/guides/5-request-client/1-payment-networks.md, packages/docs/package.json, packages/docs/src/components/supported-erc20/index.js, packages/docs/src/components/supported-erc20/styles.module.css, yarn.lock
Add a helper to the docs to list all the supported ERC20 tokens.
=> docs: add listed ERC20 helper to docs

packages/request-node/src/request/confirmedTransactionStore.ts, packages/request-node/src/requestNode.ts, packages/request-node/src/storageUtils.ts
Store confirmed transactions on keyv
=> feat: store confirmed transactions

packages/payment-detection/src/btc/mainnet-address-based.ts, packages/payment-detection/src/btc/testnet-address-based.ts, packages/payment-detection/src/declarative.ts, packages/payment-detection/src/erc20/address-based.ts, packages/payment-detection/src/erc20/proxy-contract.ts, packages/payment-detection/src/eth/input-data.ts, packages/payment-detection/test/btc/mainnet-address-based.test.ts, packages/payment-detection/test/btc/testnet-address-based.test.ts, packages/payment-detection/test/declarative.test.ts, packages/payment-detection/test/erc20/address-based.test.ts, packages/payment-detection/test/erc20/proxy-contract.test.ts, packages/payment-detection/test/eth/input-data.test.ts, packages/request-client.js/src/api/request-network.ts, packages/types/src/payment-types.ts, packages/utils/src/crypto.ts, packages/utils/test/crypto.test.ts
Fix from the suggestion RN-01-001 WP1 of the audit of Cure+53
=> chore: replace Math.random by random32Bytes

packages/advanced-logic/specs/payment-network-erc20-fee-proxy-contract-0.1.0.md
Create specs for a Payment Network that allow the payment and detection of fees
on ERC20, using a proxy smart-contract.
https://requestnetwork.atlassian.net/browse/PROT-1218
=> docs: create specs for ERC20 fee proxy-contract PN

packages/smart-contracts/README.md, packages/smart-contracts/artifacts/ERC20FeeProxy/0.1.0.json, packages/smart-contracts/artifacts/ERC20FeeProxy/artifacts.json, packages/smart-contracts/migrations/2_deploy_contracts.js, packages/smart-contracts/src/contracts/ERC20FeeProxy.sol, packages/smart-contracts/src/lib/erc20FeeProxyArtifact.ts, packages/smart-contracts/test/contracts/ERC20FeeProxy.js, packages/smart-contracts/tsconfig.json
Create the smart contract to handle ERC20 fees
https://requestnetwork.atlassian.net/browse/PROT-1218
=> feat: create ERC20 fees smart contract

packages/advanced-logic/specs/payment-network-erc20-fee-proxy-contract-0.1.0.md, packages/advanced-logic/src/advanced-logic.ts, packages/advanced-logic/src/extensions/payment-network/erc20/fee-proxy-contract.ts, packages/advanced-logic/src/extensions/payment-network/reference-based.ts, packages/advanced-logic/test/extensions/payment-network/erc20/fee-proxy-contract.test.ts, packages/advanced-logic/test/utils/payment-network/erc20/fee-proxy-contract-add-data-generator.ts, packages/advanced-logic/test/utils/payment-network/erc20/fee-proxy-contract-create-data-generator.ts, packages/smart-contracts/src/contracts/ERC20FeeProxy.sol, packages/smart-contracts/test/contracts/ERC20FeeProxy.js, packages/types/src/extension-types.ts
Create advanced-logic extension for ERC20 fees payment network.
=> feat: ERC20 fees payment network extension

packages/payment-processor/src/contracts/Erc20FeeProxyContract.ts, packages/payment-processor/src/payment/erc20-fee-proxy.ts, packages/payment-processor/src/payment/erc20-proxy.ts, packages/payment-processor/src/payment/utils.ts, packages/payment-processor/test/payment/erc20-fee-proxy.test.ts, packages/smart-contracts/artifacts/ERC20FeeProxy/0.1.0.json, packages/smart-contracts/src/lib/index.ts
Add payment-processor support to ERC20 with fees proxy contract
=> feat: add erc20 proxy with fee payment processor

packages/advanced-logic/src/advanced-logic.ts, packages/payment-detection/src/erc20/fee-proxy-contract.ts, packages/payment-detection/src/erc20/index.ts, packages/payment-detection/src/erc20/proxy-info-retriever.ts, packages/payment-detection/src/payment-network-factory.ts, packages/payment-detection/test/erc20/fee-proxy-contract.test.ts, packages/smart-contracts/src/lib/erc20FeeProxyArtifact.ts, packages/smart-contracts/src/lib/index.ts, packages/types/src/payment-types.ts
Add payment detection to the ERC20 fee proxy contract.
TODO: missing adding the fee balance to the request.
=> feat: add ERC20 fee proxy contract PN payment detection

packages/payment-detection/src/erc20/fee-proxy-contract.ts, packages/payment-detection/src/erc20/proxy-info-retriever.ts, packages/payment-detection/test/erc20/fee-proxy-contract.test.ts
Add fee balance calculation to payment ERC20 Fee proxy Payment network.
=> feat: calculate ERC20 fee balance

packages/advanced-logic/src/advanced-logic.ts, packages/payment-detection/src/erc20/proxy-info-retriever.ts, packages/payment-detection/src/payment-network-factory.ts, packages/payment-detection/test/erc20/proxy-info-retriever.test.ts, packages/payment-processor/src/index.ts, packages/payment-processor/src/payment/erc20-fee-proxy.ts, packages/payment-processor/src/payment/erc20-proxy.ts, packages/payment-processor/src/payment/index.ts, packages/payment-processor/test/payment/erc20-fee-proxy.test.ts
Fix a few missing exports and a few bugs on ERC20 Fee Payment Network implementation.
=> fix: fix bugs and missing exports for ERC20 fee payment network

packages/docs/docs/guides/5-request-client/2-erc20-payment-detection.ts, packages/docs/docs/guides/5-request-client/3-eth-payment-detection.ts, packages/docs/docs/guides/5-request-client/4-btc-payment-detection.ts, packages/docs/docs/guides/5-request-client/5-declarative-payment-network.ts, packages/docs/docs/guides/5-request-client/7-encryption.md, packages/docs/docusaurus.config.js, packages/docs/package.json, packages/docs/src/css/custom.css, yarn.lock
Upgrade docusaurus so it stops breaking the build.
Also fix some minor mistakes on the doc.
=> chore: upgrade docs

packages/docs/docs/guides/4-request-payment/0-intro.md
=> docs: eth-rinkeby

packages/ethereum-storage/src/gas-price-definer.ts, packages/ethereum-storage/src/gas-price-providers/etherchain-provider.ts, packages/ethereum-storage/src/gas-price-providers/etherscan-provider.ts, packages/ethereum-storage/src/gas-price-providers/ethgasstation-provider.ts, packages/ethereum-storage/test/gas-price-providers/etherscan-provider.test.ts
Add etherscan as a gas oracle provider
=> feat: add etherscan gas oracle provider

yarn.lock
=> chore: fix docusaurus-typedoc yarn.lock

packages/integration-test/test/node-client.test.ts, packages/payment-detection/test/eth/input-data.test.ts, packages/request-client.js/test/ethers-mockup.ts, packages/request-client.js/test/index.test.ts
=> test: unskip tests and mock etherscan calls

packages/data-format/src/format/rnf_invoice/rnf_invoice-0.0.3.json, packages/data-format/test/data/example-invalid-0.0.3.json, packages/data-format/test/data/example-valid-0.0.3.json, packages/data-format/test/test.ts
rnf invoice data type 3.0, grouping of tax
https://app.asana.com/0/1194620076282706/1196258233315537
=> feat: rnf invoice data format 3, grouped tax

packages/smart-contracts/artifacts/ERC20SwapToPay/artifacts.json, packages/smart-contracts/artifacts/verification/ERC20SwapToPay.sol/ERC20FeeProxy.sol, packages/smart-contracts/artifacts/verification/ERC20SwapToPay.sol/ERC20SwapToPay.sol, packages/smart-contracts/artifacts/verification/ERC20SwapToPay.sol/SafeERC20.sol, packages/smart-contracts/src/contracts/ERC20SwapToPay.sol, packages/smart-contracts/src/contracts/lib/SafeERC20.sol, packages/smart-contracts/test/contracts/ERC20SwapToPay.js
* Fix the transfer of USDT in the case of USDT > ERC20 swaps to pay
* Also fix a bug that would occur if we needed to increase the approval of USDT for one of the 2 contracts
=> fix: UDST.transfer

packages/payment-processor/src/payment/index.ts, packages/payment-processor/test/payment/index.test.ts
* Smart contract wallets do not need to have ETH for the payment are the gas is paid by an EOA
https://app.asana.com/0/1199139651874074/1199241446145269/f
=> feat: smart contract wallets do not need eth to pay gas

packages/request-client.js/src/api/currency/erc20.ts, packages/request-client.js/test/api/currency.test.ts
Add support for additional ERC20 tokens that aren't on the Metamask Contract list.
=> feat: Add extra support erc20 tokens

packages/payment-processor/src/payment/erc20.ts
Add the Signer object as provider for the erc20 approval
=> fix: Add Signer as provider for the erc20 approval

packages/currency/package.json, packages/docs/package.json, yarn.lock
https://requestnetwork.atlassian.net/browse/PROT-
=> chore: upgrade contract-metadata

packages/currency/src/erc20/networks/mainnet.ts
Added 2 tokens: 88mph.app MPH and Aave USDC.
=> feat: add mph and ausdc tokens to supported tokens

packages/payment-detection/src/any/any-to-erc20-proxy-contract.ts, packages/payment-detection/src/erc20/fee-proxy-contract.ts, packages/payment-detection/test/any/any-to-erc20-proxy-contract.test.ts, packages/types/src/extensions/pn-any-to-er20-types.ts
=> chore: refactor the payment detection for onchain conversion requests

packages/payment-detection/package.json
=> fix: Update currency package dependency in payment-detection

packages/payment-processor/src/payment/index.ts
Importing ICurrency from types/RequestLogicTypes so that further extensions can be supported
=> chore: use ICurrency import from request-logic-types instead of dist

packages/advanced-logic/src/extensions/payment-network/any-to-erc20-proxy.ts
=> fix: acceptedTokens addresses are normalized in lower case

packages/smart-contracts/test/contracts/ChainlinkConversionPath.js
=> test: added 2 tests for ETH based on-chain conversion

packages/advanced-logic/specs/advanced-logic-specs-0.1.0.md
fix broken link
no access to :
https://requestnetwork.atlassian.net/
=> docs: update link to request logic specifications

packages/ethereum-storage/src/config.ts, packages/ethereum-storage/src/ethereum-utils.ts, packages/ethereum-storage/src/gas-price-definer.ts, packages/ethereum-storage/src/gas-price-providers/xdai-fixed-provider.ts, packages/ethereum-storage/src/smart-contract-manager.ts, packages/ethereum-storage/test/ethereum-utils.test.ts, packages/ethereum-storage/test/gas-price-definer.test.ts, packages/ethereum-storage/test/gas-price-providers/xdai-fixed-provider.test.ts, packages/types/src/storage-types.ts
I took the opportunity to clean a little some stuff related to gas price.
The gas price is now always a BigNumber.
=> feat: xdai gas price

packages/request-client.js/src/api/request-network.ts, packages/request-client.js/src/api/request.ts, packages/types/src/client-types.ts
when these events are not used, they can cause side effects, like leakage in tests
=> feat: optionally disable events

packages/advanced-logic/src/extensions/payment-network/any-to-erc20-proxy.ts, packages/currency/src/chainlink-path-aggregators.ts, packages/toolbox/README.md
=> feat: updated aggregators for AUD and CAD

packages/advanced-logic/src/extensions/payment-network/any-to-erc20-proxy.ts, packages/currency/src/chainlink-path-aggregators.ts, packages/payment-processor/src/payment/index.ts, packages/toolbox/src/chainlinkConversionPathTools.ts
I think that we should publish a release after this merge.
=> feat: SAND aggregator support for conversion

packages/currency/src/token.ts, packages/currency/test/currency.test.ts, packages/currency/test/token.test.ts
=> fix: Token.from('FAU-rinkeby')

packages/advanced-logic/src/extensions/payment-network/any-to-erc20-proxy.ts, packages/advanced-logic/test/utils/payment-network/erc20/any-to-erc20-proxy-create-data-generator.ts, packages/payment-processor/src/payment/any-to-erc20-proxy.ts, packages/payment-processor/src/payment/conversion-erc20.ts, packages/payment-processor/src/payment/swap-any-to-erc20.ts, packages/payment-processor/src/payment/swap-conversion-erc20.ts
=> refactor: get default network from advanced logic

packages/currency/src/erc20/networks/mainnet.ts, packages/currency/test/currency.test.ts, packages/currency/test/currency/erc20.test.ts, packages/currency/test/token.test.ts
=> fix: other references to MPH address

packages/advanced-logic/src/extensions/payment-network/erc20/fee-proxy-contract.ts, packages/payment-detection/src/payment-network-factory.ts, packages/smart-contracts/src/lib/artifacts/ERC20FeeProxy/index.ts
Pending on Smart Contract deployment
=> feat: ERC20 Fee Proxy on Matic

packages/payment-detection/src/erc20/fee-proxy-contract.ts, packages/smart-contracts/src/lib/ContractArtifact.ts
One of the 2 changes would be sufficient. But it's cleaner this way
=> fix: this undefined for fee-proxy-contract

packages/advanced-logic/src/extensions/payment-network/any-to-erc20-proxy.ts, packages/currency/src/chainlink-path-aggregators.ts
=> feat: ARKO on-chain conversion

packages/currency/src/erc20/networks/celo.ts
* cGLD: Celo Gold token
* cEUR: Celo Euro
=> feat: added cGLD and cEUR on celo network

packages/advanced-logic/src/extensions/payment-network/erc20/fee-proxy-contract.ts, packages/smart-contracts/src/lib/artifacts/ERC20FeeProxy/index.ts
- Add Celo payment detection on testnet alfajores
- Add Fuse payment detection contract support with first test, will be redeployed later from common deployer
=> feat: ERC20 Fee Proxy on Celo and Fuse

packages/payment-detection/src/index.ts, packages/payment-detection/src/thegraph/queries/GetLastSyncedBlock.graphql
=> feat: TheGraph get last synced block

packages/ethereum-storage/src/gas-price-providers/xdai-fixed-provider.ts, packages/ethereum-storage/test/gas-price-providers/xdai-fixed-provider.test.ts
=> feat: increase XDaiFixedProvider prices

package.json, packages/currency/package.json, packages/data-format/package.json, packages/docs/package.json, packages/ethereum-storage/package.json, packages/integration-test/package.json, packages/payment-detection/package.json, packages/payment-processor/package.json, packages/payment-processor/test/payment/eth-proxy.test.ts, packages/request-client.js/package.json, packages/smart-contracts/package.json, packages/toolbox/package.json, packages/types/package.json, packages/usage-examples/package.json, packages/utils/package.json, packages/web3-signature/package.json, yarn.lock
=> fix: upgrade ethers to 5.2.0

packages/integration-test/test/node-client.test.ts, packages/payment-detection/src/declarative.ts, packages/request-client.js/src/api/request.ts, packages/request-client.js/test/index.test.ts, packages/types/src/extensions/pn-any-declarative-types.ts
=> feat: add delegate in request client

packages/payment-detection/package.json, packages/payment-detection/src/eth/info-retriever.ts, packages/payment-detection/src/eth/input-data.ts, packages/payment-detection/src/eth/multichainExplorerApiProvider.ts, packages/payment-detection/src/eth/near-info-retriever.ts, packages/payment-detection/test/eth/info-retriever.test.ts, yarn.lock
=> feat: detect payments on near

packages/advanced-logic/specs/payment-network-eth-input-data-0.2.0.md, packages/currency/src/native.ts, packages/payment-detection/src/eth/index.ts, packages/payment-detection/src/eth/near-info-retriever.ts, packages/payment-detection/src/index.ts, packages/payment-detection/test/eth/info-retriever.test.ts, packages/payment-processor/package.json, packages/payment-processor/src/index.ts, packages/payment-processor/src/payment/index.ts, packages/payment-processor/src/payment/near-input-data.ts, packages/payment-processor/src/payment/utils-near.ts, packages/payment-processor/test/payment/index.test.ts, yarn.lock
Process Near payments with the `near-api-js` library.
Breaking changes: `connector` is encapsulated within `connectOptions` for methods `hasSufficientFunds` and `isSolvent`.
=> feat: process near payments

packages/request-client.js/webpack.config.js
- Fixing the broken `next-release` job due to `pg` dependency.
=> fix: webpack for postgre

packages/advanced-logic/src/extensions/payment-network/address-based.ts, packages/payment-detection/src/reference-based-detector.ts
=> fix: imports from types package

packages/payment-detection/src/near-detector.ts
- [Near native token proxy deployed](https://explorer.near.org/accounts/requestnetwork.near)
=> feat: near mainnet deployment info

package.json
cf. https://github.com/RequestNetwork/requestNetwork/pull/609 but does the opposite.
=> feat: yarn unlink:all

packages/payment-detection/src/declarative.ts, packages/payment-detection/test/declarative.test.ts, packages/types/src/payment-types.ts
`txHash` should be added to balance parameters
=> fix: add txHash to balance

.github/workflows/docs-deploy-staging.yml, packages/docs/package.json, yarn.lock
Reverts RequestNetwork/requestNetwork#661
=> fix: revert PR 661

packages/advanced-logic/test/extensions/payment-network/declarative.test.ts, packages/advanced-logic/test/utils/payment-network/any/generator-data-create.ts
=> test: add txHash and network in parameters test

packages/smart-contracts/hardhat.config.ts, packages/smart-contracts/scripts/2_deploy-main-payments.ts, packages/smart-contracts/scripts/4_deploy-escrow-deployment.ts, packages/smart-contracts/src/contracts/ERC20EscrowToPay.sol, packages/smart-contracts/test/contracts/ERC20EscrowToPay.test.ts
feat: Erc20EscrowToPay (contract & tests only)
This is a squashed version of previous PR #624
=> feat: EscrowToPayV1 

packages/smart-contracts/hardhat.config.ts, packages/smart-contracts/scripts/utils.ts, packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20FeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20SwapToPay/index.ts, packages/smart-contracts/src/lib/artifacts/Erc20ConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/Erc20SwapConversion/index.ts, packages/smart-contracts/src/lib/artifacts/EthConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumFeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumProxy/index.ts
=> feat: standard deployments on celo

packages/request-node/package.json, packages/request-node/src/storageUtils.ts, yarn.lock
- Allow usage of websocket connection string in `WEB3_PROVIDER_URL` or `argv.providerUrl` for the request-node
- Handles heartbeats/keepalive
=> feat(request-node): allow ws connection

packages/payment-processor/src/index.ts, packages/payment-processor/src/payment/erc20-escrow-payment.ts, packages/payment-processor/test/payment/erc20-escrow-payment.test.ts, packages/smart-contracts/src/lib/artifacts/ERC20EscrowToPay/0.1.0.json, packages/smart-contracts/src/lib/artifacts/ERC20EscrowToPay/index.ts, packages/smart-contracts/src/lib/artifacts/index.ts
This is a squashed version of previous PR #675.
Feat: payment-processing files for erc20EscrowToPay smart-contract.
=> feat: Erc20 escrow payment processor (complete w/tests). 

packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20FeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20SwapToPay/index.ts, packages/smart-contracts/src/lib/artifacts/Erc20ConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/Erc20SwapConversion/index.ts, packages/smart-contracts/src/lib/artifacts/EthConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumFeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumProxy/index.ts
=> feat: deployment for mainnet up to EthConversionProxy

packages/payment-detection/src/eth/input-data.ts
Payment network eth-input-data uses theGraph for payments via EthProxy.
Just one question for @benjlevesque, you recently updated mainnet subgraph if I remember correctly.
So is [this function](https://github.com/RequestNetwork/requestNetwork/blob/562e24a49b68e2d09d968581f93848fd8fa3fa3f/packages/payment-detection/src/thegraph/index.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L37) obsolete now.
=> Payment network eth-input-data uses theGraph for payments via EthProxy

packages/payment-detection/src/provider.ts
This has proven to be more stable in our stack
=> chore(payment-detection): switch to rpc.ftm.tools for fantom

packages/currency/package.json, yarn.lock
Update the metamask contract list - needed for DATA. 
https://github.com/MetaMask/contract-metadata/pull/943
=> chore: upgrade metamask contract package

.circleci/config.yml
Light optimization to improve speed:
- doc: https://circleci.com/docs/2.0/executor-types/#ram-disks
- blog: https://blog.kewah.com/2021/faster-circleci-pipeline-using-the-ram-disk/
=> ci: use ram disk

packages/smart-contracts/scripts/deploy-one.ts, packages/smart-contracts/scripts/utils.ts
- No Uniswap V2 on Arbitrum
- Minor fix for deployment script
=> chore: minor deployment script improvement

packages/payment-processor/src/payment/any-to-eth-proxy.ts
=> fix: ETH mainnet hash on any chain for conversion

packages/smart-contracts/scripts/deploy-payments.ts, packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/index.ts, packages/smart-contracts/src/lib/artifacts/EthConversionProxy/index.ts
=> feat(artifacts): ETHConversionProxy v2 on Rinkeby

packages/smart-contracts/scripts/deploy-payments.ts, packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/index.ts, packages/smart-contracts/src/lib/artifacts/EthConversionProxy/index.ts
=> feat(artifacts): ETHConversionProxy v2 on Fantom

packages/advanced-logic/src/extensions/payment-network/any-to-eth-proxy.ts, packages/advanced-logic/test/extensions/payment-network/any-to-eth-proxy.test.ts, packages/payment-detection/src/any/any-to-eth-proxy.ts
=> feat: default version is 0.2.0 for AnyToEthProxy

packages/payment-processor/src/payment/any-to-eth-proxy.ts, packages/smart-contracts/src/lib/ContractArtifact.ts
=> fix: revert eth mainnet for conversion

packages/advanced-logic/src/extensions/payment-network/erc20/fee-proxy-contract.ts, packages/advanced-logic/src/extensions/payment-network/ethereum/input-data.ts, packages/payment-detection/src/provider.ts, packages/smart-contracts/scripts/utils.ts
Updates the request network library to support arbitrum-one
=> feat: arbitrum-one support

packages/payment-detection/package.json, packages/payment-detection/src/any/any-to-erc20-proxy.ts, packages/payment-detection/src/any/any-to-eth-proxy.ts, packages/payment-detection/src/any/retrievers/thegraph.ts, packages/payment-detection/src/eth/fee-proxy-detector.ts, packages/payment-detection/src/eth/input-data.ts, packages/payment-detection/src/thegraph/index.ts, packages/payment-detection/src/thegraph/queries/GetConversionPayments.graphql, packages/payment-detection/test/any/any-to-eth.test.ts, packages/payment-detection/tsconfig.json
Changes
- all networks use TheGraph
- AnyToEth retriever with TheGraph
- tests for AnyToEth
=> feat: enable TheGraph on all networks

packages/smart-contracts/hardhat.config.ts, packages/smart-contracts/src/lib/artifacts/ERC20FeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumProxy/index.ts
=> chore: deployment info for Fuse up to ETHProxy

packages/currency/src/chainlink-path-aggregators.ts
=> fix: conversion for arbitrum

packages/request-node/src/thegraph/TheGraphStorage.ts
Fixed computation of `maxFeePerGas`.
=> fix(request-node): maxFeePerGas calculation

packages/payment-detection/src/eth/multichainExplorerApiProvider.ts
=> fix: arbiscan API

packages/data-format/src/format/rnf_invoice/utils.ts, packages/data-format/test/rnf_invoice/utils.test.ts
It adds new methods for calculating tax amount in a consistent way as well as the corresponding tests.
Making these methods available in the package ensure that we always calculate taxes with the same method.
=> fix: tax calculation 

packages/data-format/src/format/rnf_invoice/utils.ts, packages/data-format/test/rnf_invoice/utils.test.ts
`BigNumber.from(Number(x))` introduced an issue for large input.
I added a new test case to prevent from this error in the future
=> fix: tax calculation

packages/epk-decryption/webpack.config.js, packages/epk-signature/webpack.config.js, packages/request-client.js/webpack.config.js, packages/web3-signature/webpack.config.js
This is a follow up to https://github.com/RequestNetwork/requestNetwork/pull/778 as I forgot to change the webpack configuration before.
=> fix: webpack ts-loader build conf

.github/semantic.yml
Adds a config file for the [semantic-pull-requests](https://github.com/zeke/semantic-pull-requests) bot in order to always check the title of PRs, because we only allow "squash and merge".
=> ci: semantic PR title

packages/advanced-logic/specs/payment-network-any-to-erc20-proxy-0.1.0.md
=> spec(advanced-logic): remove path references

packages/currency/src/native.ts, packages/smart-contracts/hardhat.config.ts, packages/smart-contracts/scripts/deploy-payments.ts, packages/smart-contracts/scripts/utils.ts, packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20FeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20SwapToPay/index.ts, packages/smart-contracts/src/lib/artifacts/Erc20ConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/Erc20SwapConversion/index.ts, packages/smart-contracts/src/lib/artifacts/EthConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumFeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumProxy/index.ts
- Full deployment on Avalanche
- Small fix on the deployment script (nonce jump)
=> feat: deployment information for Avalanche

packages/advanced-logic/src/extensions/payment-network/erc20/fee-proxy-contract.ts, packages/advanced-logic/src/extensions/payment-network/ethereum/input-data.ts, packages/currency/src/chainlink-path-aggregators.ts, packages/payment-detection/src/eth/multichainExplorerApiProvider.ts, packages/payment-detection/src/provider.ts
Contract addresses as well as native currency were updated in https://github.com/RequestNetwork/requestNetwork/pull/795
=> feat: avalanche network

packages/smart-contracts/scripts/conversion-proxy.ts, packages/smart-contracts/scripts/deploy-one.ts, packages/smart-contracts/scripts/deploy-payments.ts, packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/index.ts, packages/smart-contracts/src/lib/artifacts/EthConversionProxy/index.ts
Deployment of Chainlink Aggregator Path 0.2.0 on Celo and Matic
Deployment of ETH Conversion Proxy 0.2.0 on Celo and Matic
=> depl: conversion proxies 0.2.0 to Celo and Matic

packages/payment-detection/test/eth/info-retriever.test.ts
=> chore: temporary disable Sokol from Retriever tests

packages/payment-detection/src/index.ts, packages/payment-detection/src/utils.ts, packages/payment-detection/test/utils.test.ts
Function for parsing through escrow events and computing the final escrow state
=> feat: exporting calcEscrowState function from payment-detection

packages/payment-detection/src/provider.ts, packages/payment-detection/test/provider.test.ts, packages/smart-contracts/hardhat.config.ts, packages/smart-contracts/package.json, packages/toolbox/src/commands/chainlink/addAggregators.ts, packages/toolbox/src/commands/chainlink/aggregatorsUtils.ts, yarn.lock
(smart-contracts)chore: Hardhat Etherscan v3 for a better handling of explorer API keys
(toolbox)chore: addAggregators with listAll option
(payment-detection)chore: Polygon RPC fix according to [Polygon's documentation](https://docs.polygon.technology/docs/develop/network-details/network/)
=> chore: hardhat-etherscan 3 and addAggregators --listAll

packages/payment-detection/codegen-near.yml, packages/payment-detection/package.json, packages/payment-detection/src/index.ts, packages/payment-detection/src/near-detector.ts, packages/payment-detection/src/near-info-retriever.ts, packages/payment-detection/src/thegraph/index.ts, packages/payment-detection/src/thegraph/queries/near/GetPayments.graphql, packages/payment-detection/test/near-native.test.ts, packages/payment-processor/src/payment/utils-near.ts, yarn.lock
=> chore: detect near mainnet payments with a subgraph

packages/smart-contracts/scripts/deploy-payments.ts, packages/smart-contracts/scripts/utils.ts, packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/index.ts, packages/smart-contracts/src/lib/artifacts/Erc20ConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthConversionProxy/index.ts
* Deployed ETH Conversion proxy with ABI 0.1.1 in order to change the proxy and use the ETHFeeProxy 0.3.0
=> chore: ETHConversion proxy ownership transferred

packages/advanced-logic/src/advanced-logic.ts, packages/advanced-logic/src/extensions/payment-network/address-based.ts, packages/advanced-logic/src/extensions/payment-network/erc777/stream.ts, packages/advanced-logic/test/extensions/payment-network/erc777/stream.test.ts, packages/advanced-logic/test/utils/payment-network/erc777/stream-add-data-generator.ts, packages/advanced-logic/test/utils/payment-network/erc777/stream-create-data-generator.ts, packages/currency/src/types.ts, packages/integration-test/.vscode/launch.json, packages/integration-test/.vscode/settings.json, packages/integration-test/test/scheduled/erc777-stream.test.ts, packages/integration-test/test/scheduled/mocks.ts, packages/payment-detection/src/erc777/superfluid-detector.ts, packages/payment-detection/src/erc777/superfluid-retriever.ts, packages/payment-detection/test/eth/info-retriever.test.ts, packages/types/src/extension-types.ts, packages/types/src/extensions/pn-any-stream-reference-based-types.ts, packages/types/src/payment-types.ts, packages/types/src/request-logic-types.ts
superfluid advanced-logic for the 1st request of a series
=> feat: SuperFluid advanced logic

packages/smart-contracts/README.md
=> docs(smart-contracts): fix readme link

packages/smart-contracts/src/lib/artifacts/BatchPayments/index.ts
=> feat(smart-contracts): Batch payment on rinkeby

packages/currency/src/currencyManager.ts, packages/currency/src/erc777/index.ts, packages/currency/src/erc777/networks/index.ts, packages/currency/src/erc777/networks/rinkeby.ts, packages/currency/src/index.ts, packages/currency/test/currency/erc777.test.ts, packages/currency/test/currencyManager.test.ts
Adding ERC777 currency support for SuperFluid integration.
=> feat: add ERC777 currency support

packages/currency/src/currency-utils.ts, packages/currency/src/types.ts
This allows to easily determine the type of a currency but also correctly type an array of currencies when filtered.
=> feat: currency type guards

packages/integration-test/test/scheduled/erc20-address-based.test.ts, packages/integration-test/test/scheduled/erc20-mainnet-test-data.ts
Fixed the failing nightly tests, there was 1 extra transaction in one of the test addresses
=> fix: fixed failing test, added expected payment event

packages/smart-contracts/README.md, packages/smart-contracts/src/lib/artifacts/ERC20EscrowToPay/index.ts
Adding escrow configs for matic and bsc
=> chore: escrow configs

packages/request-node/src/thegraph/queries.ts
Adding a name for easy mocking
=> fix(graph node): graphql query name

packages/payment-detection/src/erc20/thegraph-info-retriever.ts
ticket: https://app.asana.com/0/1187210138355031/1202055267731943/f
- small update to include the `from` field in the payment event
=> feat: pull from field from subgraph

packages/payment-detection/src/any/retrievers/thegraph.ts, packages/payment-detection/src/thegraph/queries/GetConversionPayments.graphql, packages/payment-detection/test/any/any-to-erc20-proxy-contract.test.ts, packages/payment-detection/test/any/any-to-eth.test.ts, packages/payment-detection/test/erc20/proxy-contract.test.ts
ticket: https://app.asana.com/0/1187210138355031/1202055267731943/f
- added more test & updated query (AnyToERC20PaymentDetector, AnyToEthFeeProxyPaymentDetector, ERC20ProxyPaymentDetector)
=> feat: pull gas info from subgraph on other payment networks

packages/smart-contracts/src/contracts/ERC20EscrowToPay.sol, packages/smart-contracts/test/contracts/ERC20EscrowToPay.test.ts
=> fix: escrow audit fix 2

packages/smart-contracts/src/lib/artifacts/ERC20EscrowToPay/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20FeeProxy/index.ts
=> chore: update escrow addresses

packages/currency/src/aggregators/goerli.json, packages/currency/src/chainlink-path-aggregators.ts, packages/payment-detection/test/any/any-to-erc20-proxy-contract.test.ts, packages/payment-detection/test/provider.test.ts, packages/payment-processor/test/payment/utils.test.ts
factorize some goerli tests with testSuite and add chainlinkPathAggregators
=> refactor: factorize goerli tests

packages/advanced-logic/specs/payment-network-any-declarative-0.2.0.md, packages/payment-detection/src/declarative.ts, packages/request-client.js/test/index.test.ts, packages/types/src/extensions/pn-any-declarative-types.ts, packages/types/src/payment-types.ts
Enable having a payment reference on a declarative request
=> feat(declarative): payment reference

packages/payment-detection/src/erc777/superfluid-retriever.ts
Switch back the block type to number.
=> fix: superfluid block type

.github/workflows/docs-deploy-prod.yml
add GitHub Action to deploy docs to prod but only triggered manually and managing the S3 bucket as input instead of secret.
=> feat: add GitHub Action to deploy docs to prod

packages/smart-contracts/src/lib/artifacts/BatchConversionPayments/index.ts
=> fix(smart-contract): batch conversion - add xdai and fuse proxy addresses

packages/currency/src/aggregators/goerli.json, packages/currency/src/conversion-aggregators.ts, packages/currency/src/erc20/networks/goerli.ts, packages/currency/src/erc20/networks/index.ts, packages/toolbox/src/commands/chainlink/aggregatorsUtils.ts
- feat: support ETH and DAI Chainlink aggregators on goerli (DAI is mapped to FAU)
- fix: the aggregators feed map (the format changed)
- fix: FAU-goerli
=> feat: goerli aggregators

packages/payment-detection/src/near/near-conversion-detector.ts, packages/payment-detection/test/near/near-native-conversion.test.ts, packages/payment-processor/src/payment/near-conversion.ts, packages/payment-processor/src/payment/utils-near.ts, packages/payment-processor/src/payment/utils.ts, packages/payment-processor/test/payment/any-to-near.test.ts, packages/types/src/request-logic-types.ts
Payment processor for any-to-near (only the commit starting from `near payment with conversion`
[Asana task](https://app.asana.com/0/1202922067864171/1202201668706294)
[x] [This PR](https://github.com/RequestNetwork/requestNetwork/pull/922) should be merged first to limit conflicts
=> feat: near conversion payment processor

packages/ethereum-storage/src/ethereum-storage-ethers.ts, packages/payment-detection/test/eth/info-retriever.test.ts
this should avoid getting errors when `maxPriorityFeePerGas` is 0
=> fix: min gas

packages/request-node/src/thegraph-node.ts
Ethers calls `mainnet` `homestead`
=> fix(request node): wrong network name for mainnet

packages/payment-processor/package.json, packages/payment-processor/src/payment/erc20-escrow-payment.ts, packages/payment-processor/src/payment/erc777-stream.ts, packages/payment-processor/src/payment/erc777-utils.ts, packages/payment-processor/test/payment/erc777-stream.test.ts, yarn.lock
Adds payment processor logic and tests for superfluid one-off payment.
Also adds the intermediary prepare function for escrow approval/payment and superfluid wrapping/unwrapping.
=> feat: superfluid one off payment processor

packages/payment-detection/src/payment-network-factory.ts, packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/index.ts
Follow-up for [this fix](https://github.com/RequestNetwork/requestNetwork/pull/975) after fixing the chain at the creation level
=> fix: getPaymentNetworkFrom conversion request

packages/payment-detection/src/erc777/superfluid-retriever.ts, packages/payment-detection/src/thegraph/queries/superfluid/GetSuperFluidEvents.graphql, packages/payment-detection/test/erc777/mocks.ts, packages/payment-detection/test/erc777/superfluid-retriever.test.ts
Adds the detection of superfluid one-off payments
=> feat: superfluid one off payment detection

packages/smart-contracts/scripts-create2/contract-setup/adminTasks.ts, packages/smart-contracts/scripts-create2/contract-setup/setupERC20SwapToConversion.ts, packages/smart-contracts/scripts-create2/contract-setup/setupETHConversionProxy.ts, packages/smart-contracts/scripts-create2/contract-setup/setupErc20ConversionProxy.ts
=> fix(smart-contract): xdeployer setup eth conversion proxy

packages/request-node/src/config.ts, packages/request-node/src/thegraph-node.ts
fixup for https://github.com/RequestNetwork/requestNetwork/pull/997
=> chore(thegraph-node): use min gas price config

packages/currency/src/conversion-aggregators.ts, packages/currency/src/native.ts, packages/payment-detection/src/eth/multichainExplorerApiProvider.ts, packages/payment-detection/src/provider.ts, packages/smart-contracts/hardhat.config.ts, packages/smart-contracts/scripts-create2/utils.ts, packages/smart-contracts/scripts/utils.ts, packages/smart-contracts/src/lib/artifacts/BatchConversionPayments/index.ts, packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20EscrowToPay/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20FeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20SwapToPay/index.ts, packages/smart-contracts/src/lib/artifacts/Erc20ConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/Erc20SwapConversion/index.ts, packages/smart-contracts/src/lib/artifacts/EthConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumFeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumProxy/index.ts, packages/smart-contracts/src/lib/artifacts/RequestDeployer/index.ts, packages/toolbox/src/commands/chainlink/aggregatorsUtils.ts, packages/utils/src/providers.ts
Deployment on moonbeam.
Unrelated: Deployment of the batch contract on optimism - was missing.
=> feat: moonbeam

packages/ethereum-storage/src/index.ts, packages/toolbox/src/commands/chainlink/contractUtils.ts
This was often failing on matic and optmism. 
\+ waiting for confirmation of previous TX
=> fix(toolbox): addAggregator fees

packages/currency/src/currencyManager.ts, packages/currency/src/types.ts, packages/currency/test/currencyManager.test.ts, packages/request-client.js/src/api/request-network.ts, packages/request-client.js/test/index.test.ts, packages/types/src/request-logic-types.ts
Improve the way we validate currencies on request creation.
First step for https://app.asana.com/0/1203350802794948/1203507113157162
=> fix: update currency validation

packages/smart-contracts/test/contracts/ChainlinkConversionPath.test.ts, yarn.lock
=> Made many suggested changed to subgraph docs

CONTRIBUTING.md, README.md, packages/request-client.js/README.md, yarn.lock
=> fix: replace requesthub slack with discord

packages/smart-contracts/src/lib/artifacts/ERC20TransferableReceivable/index.ts
Deployment of the contracts on goerli / matic
=> feat: erc20 transferable deployment

packages/smart-contracts/src/lib/artifacts/ERC20TransferableReceivable/index.ts
=> fix: erc20 transferable address

packages/smart-contracts/src/lib/artifacts/ERC20TransferableReceivable/index.ts
=> feat: erc20 transferable mainnet

packages/payment-processor/test/payment/erc777-stream.test.ts
The test was taking too long and failed in CI
=> fix: failing ci tests

packages/payment-detection/codegen.yml, packages/payment-detection/test/eth/info-retriever.test.ts, packages/payment-detection/test/eth/input-data.test.ts
This fixes the currently broken CI
=> fix(payment-detection): use goerli subgraph for codegen

packages/payment-detection/src/erc777/superfluid-retriever.ts, packages/payment-detection/test/erc777/superfluid-retriever.test.ts, packages/smart-contracts/scripts-create2/constructor-args.ts
=> fix: sf amount computation

.nycrc, package.json, packages/advanced-logic/.nycrc, packages/currency/.nycrc, packages/data-access/.nycrc, packages/data-format/.nycrc, packages/epk-decryption/.nycrc, packages/epk-signature/.nycrc, packages/ethereum-storage/.nycrc, packages/multi-format/.nycrc, packages/payment-detection/.nycrc, packages/payment-processor/.nycrc, packages/request-client.js/.nycrc, packages/request-logic/.nycrc, packages/request-node/.nycrc, packages/thegraph-data-access/.nycrc, packages/toolbox/.nycrc, packages/transaction-manager/.nycrc, packages/utils/.nycrc, packages/web3-signature/.nycrc, yarn.lock
The old prettier version is not compatible with a change from another big PR, so I'm created this one to clarify things a bit.
=> chore: prettier 2.8.6

packages/payment-detection/src/index.ts, packages/payment-detection/src/utils.ts, packages/payment-detection/test/erc20/thegraph-info-retriever.test.ts
This util was never used nor exported. Let's use it and export it!
=> chore(payment-detection): export hashReference util

packages/smart-contracts/README.md, packages/smart-contracts/hardhat.config.ts, packages/smart-contracts/scripts-create2/constructor-args.ts, packages/smart-contracts/scripts-create2/contract-setup/adminTasks.ts, packages/smart-contracts/scripts-create2/contract-setup/setupBatchConversionPayments.ts, packages/smart-contracts/scripts-create2/contract-setup/setupChainlinkConversionPath.ts, packages/smart-contracts/scripts-create2/contract-setup/setupERC20SwapToConversion.ts, packages/smart-contracts/scripts-create2/contract-setup/setupERC20SwapToPay.ts, packages/smart-contracts/scripts-create2/contract-setup/setupETHConversionProxy.ts, packages/smart-contracts/scripts-create2/contract-setup/setupErc20ConversionProxy.ts, packages/smart-contracts/scripts-create2/contract-setup/setups.ts, packages/smart-contracts/scripts-create2/deploy.ts, packages/smart-contracts/scripts-create2/update-contracts-setup.ts, packages/smart-contracts/scripts-create2/utils.ts
Add a new command: `yarn hardhat update-contracts`. 
The update is based on:
- A list of contracts, specified in `create2DeploymentList` from `utils.ts`
- A list of networks, specifiec in the hre config.
- Administrative values defined in `adminTasks.ts`
=> chore: improve contract administration

packages/payment-processor/src/payment/utils.ts, packages/payment-processor/test/payment/any-to-erc20-batch-proxy.test.ts, packages/payment-processor/test/payment/any-to-erc20-proxy.test.ts, packages/payment-processor/test/payment/encoder-approval.test.ts
`tokensAccepted` does not exist. the field name is `acceptedTokens`
=> fix: accepted tokens

packages/request-node/src/config.ts, packages/request-node/src/server.ts
The latest version of the node doesn't log anything due to a bug introduced in #1115
=> fix(request-node): log config

packages/smart-contracts/src/lib/artifacts/ERC20TransferableReceivable/index.ts
* Deploy ERC20TransferableReceivable v2 on Ethereum Mainnet
* Verified: https://etherscan.io/address/0xcE80D17d38cfee8E5E6c682F7712bfb5A04Ae912#code
=> chore: deploy erc20 transferable receivable v2 on ethereum

packages/payment-detection/src/index.ts
=> chore(payment-detection): export getTheGraphClient

packages/currency/src/chains/evm/data/zksync-era-testnet.ts, packages/payment-detection/src/thegraph/client.ts, yarn.lock
Updating yarn.lock with up to date package.json
And adding custom graph url for zksync Era chain
=> fix: updating yarn.lock with up to date package.json and adding custom graph url for zksync

packages/payment-detection/src/thegraph/client.ts
=> fix(payment-detection): subgraph regex

README.md
Resolves #1271
Fixes DISCORD URL from readme
=> fix(readme): invalid URL

packages/payment-processor/package.json, packages/smart-contracts/package.json, yarn.lock
This should fix https://github.com/RequestNetwork/requestNetwork/security/dependabot/182
=> chore(yarn): update @openzeppelin/contracts

package.json, yarn.lock
https://github.com/RequestNetwork/requestNetwork/security/dependabot/51
https://github.com/RequestNetwork/requestNetwork/security/dependabot/165
=> fix(security): json schema and json5

packages/currency/src/chains/evm/data/base.ts, packages/currency/src/chains/evm/index.ts, packages/currency/src/erc20/chains/base.ts, packages/types/src/currency-types.ts, packages/utils/src/providers.ts
=> feat:add base EVM chain

packages/smart-contracts/hardhat.config.ts, packages/smart-contracts/src/lib/artifacts/BatchConversionPayments/index.ts, packages/smart-contracts/src/lib/artifacts/ChainlinkConversionPath/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20FeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20Proxy/index.ts, packages/smart-contracts/src/lib/artifacts/ERC20SwapToPay/index.ts, packages/smart-contracts/src/lib/artifacts/Erc20ConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/Erc20SwapConversion/index.ts, packages/smart-contracts/src/lib/artifacts/EthConversionProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumFeeProxy/index.ts, packages/smart-contracts/src/lib/artifacts/EthereumProxy/index.ts
=> feat: base-deployment

packages/smart-contracts/src/lib/artifacts/Erc20ConversionProxy/index.ts
* Fix incorrect Erc20Conversion contract address in artifacts/index.ts file for Base.
=> fix: erc20conversion address on base

packages/payment-detection/src/thegraph/client.ts
Resolves https://github.com/RequestNetwork/requestNetwork/issues/1294
Towards https://github.com/RequestNetwork/requestNetwork/issues/1301
* add payments-subgraph URLs for Base and Core
=> chore: add payments-subgraph URLs for Base and Core

packages/request-client.js/src/api/request-network.ts, packages/request-logic/src/request-logic.ts, packages/transaction-manager/src/transaction-manager.ts
This is a fixup for #1373 
#1373 didn't make enough variables `public` to enable the Pay before Persist experiment.
* Make more variables public
=> fix: Pay before Persist experiment (Part 2)

packages/request-client.js/src/api/request-network.ts, packages/request-logic/src/request-logic.ts, packages/transaction-manager/src/transaction-manager.ts
* Revert the changes made during ETHBucharest in an attempt to enable "Pay before Persist" experiment.
This experiment was never completed it involved exposing internal implementation details of the SDK. @aimensahnoun is developing a more permanent solution in https://github.com/RequestNetwork/requestNetwork/pull/1386
=> fix: Revert Pay before Persist experiment

.github/auto_assign.yml
* Remove skiv71 from autoassign
=> chore: Remove skiv71 from autoassign

packages/payment-detection/src/thegraph/client.ts
Towards https://github.com/RequestNetwork/private-issues/issues/89
* chore: add payment subgraph URLs from Alchemy
=> chore: add payment subgraph URLs from Alchemy
